# Text Processing 실험 기록

page_classification(YOLOv11n, 93~100% 정확도)에서 has_text로 라우팅된 페이지의 실제 본문 텍스트를
얼마나 잘/빠르게 추출하는지 다루는 파트. table_processing([1]~[23])이 표를, 다른 팀원이 이미지를
맡는 구조에서, 여기는 "표도 이미지도 아닌 나머지 서술형 텍스트"가 담당 범위.

## [1] 베이스라인 기록 — PyMuPDF(+YOLO 라우팅) 완전성/정합성/리딩오더/지연 측정

**대상 PDF 2건 비교**: `reference/LGCNS/20260721_company_279243000.pdf`(6페이지, 기업분석 리포트),
`reference/Construct/20260721_industry_362851000.pdf`(10페이지, 산업 Weekly 리포트) — 섹터/형식이
다른 두 문서로 베이스라인을 잡아 특정 PDF에 과적합된 결론이 아닌지 처음부터 교차 확인.

**골든셋**: Claude가 렌더링된 페이지 이미지를 육안으로 직접 읽어 작성(추출기 출력을 베낀 게 아니라
독립적으로 재구성) — `ground_truth_text_lgcns.json`, `ground_truth_text_construct.json`. YOLOv11n의
페이지별 클래스 탐지 결과(Text/Title/Section-header/List-item/Caption vs Table/Picture)를 먼저 확인해,
**Table/Picture로 분류되는 영역(사이드바 Company Data 박스, 차트, 표)은 골든셋에서 제외** — 표는
table_processing, 차트/이미지는 다른 팀원 파트 소관이라 이중 채점을 피함.

코드: `benchmark_text_baseline.py`

### 문서 구성 관찰: 서술형 텍스트가 있는 페이지는 소수

| PDF | 전체 페이지 | 서술형 텍스트 존재 페이지 | 내용 |
|---|---|---|---|
| LG CNS | 6 | 2개(p1, p6) | p1: 애널리스트 본문(2Q26 프리뷰, 투자의견 근거), p6: Compliance Notice 법적고지 |
| Construct | 10 | 3개(p1, p5, p10) | p1: 주간 투자전략 불릿 6개, p5: 주간 뉴스 5건, p10: Compliance Notice |

나머지 페이지는 전부 표/차트(YOLO: Table/Picture) — 두 문서 모두 **증권사 리포트 특성상 서술형
텍스트가 전체 페이지의 20~30%뿐**이고 나머지는 이미 table_processing/이미지 파트가 처리하는
영역. text_processing이 다룰 실제 범위가 처음부터 생각보다 작다는 뜻.

### 리딩오더(다중 컬럼) 복원 필요성 분석

사용자가 제시한 기준(컬럼 클러스터링, 레이아웃 복잡도, 블록 겹침, 문서 유형)으로 실측 판단:

1. **문서 전체 x좌표 클러스터링**(PyMuPDF `get_text("blocks")`, gap=60pt 기준) 결과 여러 페이지에서
   2개 이상의 x클러스터가 y범위까지 겹치는 경우가 발견됨(LG CNS p1/3/5, Construct p2/3/5/6/8/9/10).
2. 하지만 **각 페이지를 렌더링해 육안으로 확인한 결과, 이 "다중 컬럼"은 전부 나란히 배치된
   표/차트**(예: LG CNS p3의 도표5+도표6, Construct p8의 3개 기업 목표주가 차트+표)였음 — 학술논문
   처럼 본문 텍스트 자체가 좌우 컬럼으로 나뉘어 흐르는 경우는 **두 문서 어디에도 없음**.
3. 실제 서술형 텍스트가 있는 5개 페이지의 골든셋 검증 결과: **본문(narrative) 단위에서는
   리딩오더 위반 0건**. 유일하게 발견된 위반 2건(LG CNS p6, Construct p10)은 전부 **법적
   고지/투자등급 정의 표 하단의 정형화된 boilerplate 섹션**에서 나온 것 — "Overweight/Neutral"
   같은 짧은 정의 항목이 한 줄에 좌우로 배치된 미세한 2단 구조 때문(예: LG CNS p6에서
   "Overweight...Neutral..."이 한 줄에 나란히 있고 "Underweight"가 다음 줄 전체폭으로 이어짐 —
   PyMuPDF 추출 순서는 Overweight→Underweight→Neutral로 나와 Neutral이 밀림).

**결론(MinerU 등 리딩오더 복원 모델 도입 여부)**: **이 두 문서 유형에는 도입 불필요**. 근거:
- 분석적으로 중요한 본문(투자의견 근거, 산업 동향, 뉴스)에서는 리딩오더 문제가 전혀 없음(0건)
- 유일한 위반은 매주 동일 템플릿으로 반복되는 일반 법적고지 정의 목록(리트리버 관점에서 가치가
  낮고, 보통 청크에서 중복 제거되거나 별도 처리되는 boilerplate)에 국한
- 반면 리딩오더 복원 모델은 페이지당 지연이 크게 늘어남(아래 3안 비교에서 YOLO 추론만으로도
  whole_page 대비 10~30배 느려짐) — 비용 대비 이득이 이 문서 유형에서는 정당화되지 않음
- **다만 팀원이 담당하는 다른 섹터/문서(잡지형·논문형 레이아웃)에서는 이 결론이 그대로
  적용되지 않을 수 있음 — 문서 유형별로 개별 판단 필요, "전부 불필요"라는 뜻은 아님**

### 추출 방식 3안 비교(Baseline)

| 방식 | 설명 |
|---|---|
| `whole_page` | 페이지 전체를 PyMuPDF `get_text()`로 통째로 추출(표/차트 구분 없음) |
| `yolo_filtered` | YOLO가 Text/Title/Section-header/List-item/Caption으로 잡은 박스만 크롭해서 추출(포지티브 선택) |
| `whole_page_masked` | 전체 추출 후 YOLO가 Table/Picture로 잡은 영역과 겹치는 블록만 제외(네거티브 마스킹) |

| 방식 | 평균 Recall(5페이지) | 평균 순도(purity) | 평균 지연 |
|---|---|---|---|
| **whole_page** | **100%(5/5 페이지 전부)** | 67.3% | **9.5ms** |
| yolo_filtered | 86.6%(3/5는 100%, 2개는 75~82%) | 76.1% | 264.3ms |
| whole_page_masked | 88.8%(4/5는 100%, 1개는 43.8%) | 87.4% | 96.5ms |

(순도 = 추출된 텍스트 중 골든 unit에 해당하는 문자 비율 — 낮을수록 표/차트 텍스트가 섞여
들어왔다는 뜻. 초기 실행에서 recall이 90% 밑으로 나온 페이지들은 재확인 결과 전부 **골든셋
자체의 구두점 표기 오류**(말줄임표 …과 ... 혼동, 곡선따옴표 '' vs 직선따옴표 '', 오타 1건)였고
파이프라인 버그가 아니었음 — 수정 후 whole_page는 5페이지 전부 100%.)

**두 필터링 방식 모두 자체 실패 모드가 실측으로 드러남**:
- `yolo_filtered`(포지티브 선택)는 boilerplate 밀집 페이지에서 recall이 떨어짐(75~82%) — List-item
  박스 탐지가 촘촘한 불릿 목록을 전부 커버하지 못해 일부 문장이 통째로 누락됨.
- `whole_page_masked`(네거티브 마스킹)는 대체로 순도가 좋아지지만(87.4%), Construct p10에서
  **recall이 43.8%까지 급락**하는 치명적 실패 발견 — "투자등급 비율공시" 표의 YOLO bbox가
  과대추정되어 바로 옆 정의 텍스트("기업의 분류", "BUY(매수)_..." 등)까지 통째로 삼켜버림
  (중심점 포함 여부만으로 판정하는 방식의 구조적 약점).

**결론(베이스라인 채택안)**: **`whole_page`를 텍스트 파이프라인 베이스라인으로 채택**. 이유:
- Recall이 가장 높고(100%) 유일하게 이번 표본에서 0건 실패
- 지연이 압도적으로 낮음(YOLO 추론이 아예 없어 9.5ms — 다른 두 방식의 1/10~1/30)
- 순도(67.3%)가 상대적으로 낮은 건 사실이나, 이는 표/차트 텍스트가 "섞여 들어오는" 문제일 뿐
  "본문이 손실/왜곡되는" 문제가 아님 — recall이 이미 100%이므로 순도는 사후 정제(예: 표/차트
  bbox와 겹침 "비율"이 threshold 이상인 경우만 제외 — 지금의 naive 중심점 포함 판정 대신)로
  개선할 별도 고도화 과제로 분리. 지금 단계에서 recall을 희생하면서까지 필터링을 서두를 이유 없음

### 신규 발견 버그: 불릿 아이콘 폰트의 PUA(Private Use Area) 글리프 매핑 실패

Construct PDF의 모든 최상위 불릿 문단이 시각적으로는 불릿 아이콘으로 보이지만, 텍스트 레이어에서는
표준 유니코드가 아닌 **Private Use Area 코드포인트**(예: `[U+F09F]`)로 추출됨:

```
'[U+F09F] 이란과 미국간의 분쟁 리스크가 일주일째 지속하고 있다...'   (p1)
'[U+F09F] 아시아 최대 규모인 2.4GW(기가와트)급 GS그룹...'           (p5)
'[U+F09F] 당사는 2026년 7월 21일 현재 해당회사의 지분을...'         (p10)
```

table_processing [19]에서 발견한 `(cid:\d+)` 글리프 매핑 실패(계약금액 숫자가 깨지는 문제)와
**같은 계열의 버그**가 텍스트 파이프라인에도 존재함을 확인 — 커스텀 아이콘/불릿 폰트가 표준
유니코드 매핑 없이 임베드된 경우 흔히 발생. 본문 CONTENT 자체는 멀쩡해서(PUA 문자는 앞에 1개
붙는 접두어라 골든셋 매칭 recall에는 영향 없음) 이번엔 완전성 문제로 이어지지 않았지만, 이
문자를 그대로 청킹/임베딩에 넣으면 노이즈 토큰이 섞이므로 **청킹 전 반드시 제거 필요**.
`benchmark_text_baseline.py`에 `detect_pua_artifact()`를 구현·검증 완료(`U+E000-U+F8FF` 범위
탐지) — **[2]에서 프로덕션 코드로 연결, 제거까지 완료.**

### 지연(latency) 비교

| 방식 | 평균 | 최소 | 최대 |
|---|---|---|---|
| whole_page | 9.5ms | 4.2ms | 18.3ms |
| whole_page_masked | 96.5ms | 89.6ms | 108.1ms |
| yolo_filtered | 264.3ms | 161.6ms | 347.5ms |

whole_page는 순수 PyMuPDF 텍스트 레이어 파싱만 하므로 ML 추론이 전혀 없어 사실상 무료(page_
classification 단계에서 이미 YOLO를 한 번 돌리므로, 이 결과를 재사용하면 whole_page_masked도
추가 추론 없이 96.5ms→거의 0에 가깝게 만들 수 있음 — 지금은 벤치마크 스크립트가 페이지분류
단계와 별도로 YOLO를 재호출해서 측정된 수치라 향후 파이프라인 연결시 이 오버헤드는 제거 가능).

### [1] 종합 판정

| 항목 | 결론 |
|---|---|
| 리딩오더 복원(MinerU 등) 필요성 | **불필요**(이 두 문서 유형 한정) — 본문에는 위반 0건, boilerplate에만 미세하게 존재 |
| 채택 베이스라인 | **whole_page(PyMuPDF `get_text()`, YOLO 필터링 없음)** — Recall 100%, 지연 9.5ms |
| 순도 개선 필요성 | 있음(67.3%) — 그러나 recall 100%를 희생하지 않는 선에서 추후 개선(표/차트 bbox와의
겹침 "비율" 기반 마스킹으로 교체 추천, 지금의 naive 중심점 포함 판정은 기각) |
| 신규 발견 이슈 | PUA 글리프 매핑 실패(불릿 아이콘) — **[2]에서 해결 완료** |
| 문서 구성 관찰 | 두 문서 모두 서술형 텍스트 페이지가 전체의 20~30%뿐 — text_processing 실제 범위가 table_processing보다 작음 |

**다음 단계(미착수, 사용자 지시 대기)**: 이번엔 "베이스라인 기록"까지만 — 순도 개선(overlap-ratio
기반 마스킹), 청킹 전략, Entity Fusion 아키텍처(텍스트→Embedding, 표/이미지→Metadata, 검색시
Dense+BM25+Metadata 결합) 등은 사용자가 참고로 제시했으나 **도입 확정 아님, 보류 상태**로 기록만
해둠 — 실제 설계는 팀 논의 후 진행.

---

## [2] PUA 글리프 제거(프로덕션 반영) + PDF 난이도 판별 라우터(easy → 우리 파이프라인 / hard → MinerU)

사용자 요청: (1) [1]에서 발견만 하고 미반영이었던 PUA 글리프 버그를 실제로 해결, (2) [1]에서
수동으로 했던 "컬럼 클러스터링 → 표/차트 오탐 제거 → boilerplate 중요도 무시" 판단 로직을
**PDF 난이도 자동 판별기**로 일반화 — 우리 파이프라인으로 처리하기 어려운(진짜 다중 컬럼 본문이
있는) PDF는 MinerU 등 외부 리더로 위임하기 위한 라우팅 근거로 사용.

### (1) PUA 글리프 제거 — `text_normalization.py`(신규)

table_processing의 `detect_cid_artifact`와 이름은 비슷하지만 대응 방식은 다르다:
- `(cid:9)`(표 파이프라인, [19]) — 숫자/문자 정보 자체가 유실. 복구 불가능하므로 **플래그만
  하고 원문 보존**(`data_quality: "unmapped_glyph"`).
- PUA 불릿 글리프(텍스트 파이프라인, 이번 건) — Construct PDF 전체 26개 발생 위치를 전수
  확인한 결과, **예외 없이** 불릿 문단 맨 앞(양쪽 공백으로 둘러싸인 독립 토큰)에만 나타나고
  뒤따르는 문장 내용은 전혀 손상되지 않음. 즉 순수 장식용 마커라 **안전하게 제거 가능** —
  `strip_pua_artifacts()`로 제거 후 중복 공백만 정리.

검증: 제거 후 골든셋 재채점 결과 LG CNS 2페이지(11/11, 11/11), Construct 3페이지(10/10, 21/21,
16/16) 전부 recall 100% 유지 — 제거가 본문 내용을 전혀 건드리지 않음을 확인.

### (2) PDF 난이도 판별 라우터 — `reading_order_router.py`(신규)

`assess_page_difficulty()` / `assess_pdf()`: [1]의 수동 분석을 그대로 알고리즘화.

1. YOLO로 페이지의 Table/Picture bbox를 먼저 구하고, 그 영역과 겹치는 텍스트 블록은 클러스터링
   대상에서 제외([1]의 1차 실패 원인 — 표/차트를 다중 컬럼으로 오탐하던 문제를 원천 차단)
2. 남은 텍스트 블록만 x0 갭(60pt) 기준으로 클러스터링
3. y범위가 겹치는(30pt 이상) 클러스터 쌍을 찾되, **양쪽 클러스터 모두 글자 수 200자 이상**일
   때만 "material"로 인정([1]에서 실제 위반이었던 "Overweight/Neutral" 한 줄짜리 정의 항목처럼
   글자수가 적은 boilerplate성 겹침은 무시 — 이게 [1]의 결론이었던 "본문엔 위반 0건, boilerplate
   에만 미세하게 존재"를 그대로 반영한 임계치)
4. material 겹침이 하나라도 있으면 `difficulty="hard"`(MinerU 위임 권장), 없으면 `"easy"`

**검증 결과**:
- LG CNS 6페이지 + Construct 10페이지 = 총 16페이지 **전부 "easy"로 정확히 판정**(`route_to_
  mineru: False`) — [1]의 결론과 100% 일치.
- **Positive 케이스 검증**: 참고 PDF에 진짜 2단 논문형 레이아웃이 없어서, PyMuPDF로 직접 만든
  합성 2단 텍스트 PDF(좌우 각 544자 분량 문단, y범위 161pt 겹침)로 별도 테스트 — **정확히
  "hard"로 판정됨**(`route_to_mineru: True`). easy/hard 양쪽 분기 모두 실측 검증 완료.

**한계(정직하게 기록)**: 실제 사용자 문서 중에는 "hard" 사례가 아직 없어, 합성 PDF 검증이
유일한 positive 케이스다. `min_chars_for_hard=200`, `gap_pt=60`, `min_y_overlap_pt=30` 임계치는
지금까지의 두 문서(증권사 리포트 포맷)에 맞춰 정한 값이라, 팀원이 다루는 잡지/논문형 실제 PDF가
들어오면 재조정이 필요할 수 있음. 또한 이 라우터는 **판정만** 하며, MinerU 호출 자체는 연동하지
않음(MinerU는 별도 팀원 도구라 이번 범위 밖) — `route_to_mineru`/`hard_page_numbers`를 반환하니
호출 측에서 해당 페이지만 MinerU로 넘기면 됨(문서 전체가 아니라 페이지 단위로 위임 — 표/차트는
그대로 우리 파이프라인이 처리하는 게 효율적이라는 판단, table_processing의 Adaptive Router와
같은 설계 철학).

### 프로덕션 진입점 — `text_extraction.py`(신규)

`extract_pdf_text(pdf_path)`: 위 두 가지를 결합한 실제 사용 인터페이스.
`assess_pdf()`로 페이지별 난이도를 먼저 매기고, `easy` 페이지는 whole_page 추출 + PUA 제거,
`hard` 페이지는 결과에 `needs_external_reader=True`로 표시만(호출자가 MinerU로 넘기도록).
아직 청킹 모듈이 없어 반환값은 "페이지 단위 정제 텍스트 + 난이도 플래그"까지 — 청킹/임베딩
연결은 다음 단계.

### [2] 종합 판정

| 항목 | 결과 |
|---|---|
| PUA 글리프 제거 | **완료** — 26개 발생 위치 전수 확인, 제거 후 골든셋 recall 100% 유지 확인 |
| 난이도 라우터 | **구현 완료**, easy/hard 양쪽 분기 모두 실측 검증(실제 문서 16페이지 전부 easy, 합성 2단 PDF는 hard) |
| 기존 PDF 2건 판정 | 전부 easy — MinerU 위임 불필요, 우리 파이프라인(whole_page)으로 충분 |
| 미해결 | 실제 hard 사례 부재(합성 데이터로만 검증), 임계치는 증권사 리포트 포맷 기준 — 다른 문서 유형 확보 시 재조정 필요 |

---

## [3] 청킹 전략 3종 비교 — 계층적(Hierarchical) vs 시멘틱(Semantic) vs 문맥적(Contextual)

whole_page 추출(recall 100%)이 확보됐으니 다음은 청킹 고도화 — 계층적/시멘틱/문맥적 3가지 방식을
실제로 구현해 비교. **평가 방법**: 각 청크를 "독립적으로"(실제 RAG에서 청크 하나만 검색되는
상황 재현) 로컬 Qwen2.5-VL-7B-Instruct에 주고 엔티티+핵심 사실을 추출시킨 뒤, 모든 청크의 추출
결과를 합쳐 골든셋(Claude가 직접 작성, `ground_truth_chunking_eval.json`) 대비 recall 계산 —
청크 경계가 "엔티티+숫자" 짝을 갈라놓으면 개별 청크 단위 추출에서 놓치는 게 그대로 드러남. 지연은
(1) 청킹 자체 구성 시간 + (2) 청크별 추출 LLM 호출 시간 합계.

**대상**: LG CNS p1(애널리스트 본문), Construct p1(주간 투자전략), Construct p5(주간 뉴스) — [1]에서
이미 검증된 골든셋 서술형 본문 재사용. 코드: `hierarchical_chunker.py`/`semantic_chunker.py`/
`contextual_chunker.py`/`evaluate_chunking.py`. **실제 청킹 결과물**: `chunks_hierarchical.json`/
`chunks_semantic.json`/`chunks_contextual.json`(3개 문서 전체) + `chunking_showcase_lgcns_p1.md`
(사람이 읽기 쉬운 예시 발췌).

### 구현 중 발견·수정한 버그 2건

1. **PyMuPDF `get_text("blocks")`가 문단이 아니라 "시각적 줄" 단위로 반환** — 계층적 청킹 초기
   구현에서 발견. 이 PDF들은 줄바꿈된 각 줄이 별도 block으로 나와서 "출 1.56조원, 영익
   1,387억원) 소폭 하회 예상. 클라우드&AI 매출은..." 처럼 문장 중간에서 청크가 끊김. [1]/[2]에서
   이미 검증된 `get_textbox(bbox)` 방식(YOLO 박스 하나 = 문단/불릿 하나)으로 교체해 해결.
2. **한국어 문장 분리기가 마침표 없는 뉴스 불릿을 처리 못함** — Construct p5(뉴스 5건, 각 항목이
   마침표 없이 줄바꿈만으로 끝남)에서 발견. 문장 종결어미(다/요/음 등) 기반 정규식만 쓰면 5개
   뉴스 항목 중 4개가 1017자짜리 "문장" 하나로 뭉쳐버려, `chunk_semantic`의 500자 상한 로직이
   무력화되고(문장 내부를 다시 쪼갤 방법이 없어서) 오버사이즈 청크가 그대로 LLM에 들어가
   max_new_tokens(120)에서 잘려 뒷부분 엔티티가 통째로 유실 — **entity_recall이 20%까지
   급락**했던 근본 원인. `split_sentences`가 줄바꿈 자체도 문장 경계로 인정하도록 수정(마침표가
   없는 리스트/불릿 콘텐츠에도 안전) — 수정 후 같은 페이지 recall이 20%→80~100%로 회복.

### 결과 — 셋 다 명확한 승자는 없음(문서마다 다름)

| 문서 | 방법 | 청크 수 | entity_recall | fact_recall | 총 지연 | 지연 세부(구성+추출) |
|---|---|---|---|---|---|---|
| **LG CNS p1** | 계층적 | 11 | 50% | 80% | 68.9s | 0.6s + 68.3s |
| | 시멘틱 | 9 | 50% | 100% | 131.9s | 12.6s + 119.2s |
| | **문맥적** | 6 | **100%** | 60% | 260.1s | 164.7s + 95.4s |
| **Construct p1** | 계층적 | 7 | 88% | **100%** | 150.4s | 0.6s + 149.8s |
| | 시멘틱 | 11 | 88% | 50% | 261.7s | 12.9s + 248.8s |
| | 문맥적 | 6 | 88% | 75% | 121.8s | 70.5s + 51.3s |
| **Construct p5** | 계층적 | 5 | **100%** | 50% | 38.2s | 0.8s + 37.4s |
| | 시멘틱 | 7 | **100%** | 75% | 59.1s | 11.3s + 47.9s |
| | 문맥적 | 4 | 80% | 50% | 181.0s | 38.6s + 142.4s |

**해석**:
- **문맥적 청킹이 유일하게 우위를 보인 사례(LG CNS p1, entity_recall 100%)는 대명사("동사"/"당사")
  문제**: LG CNS p1 후반 문단들은 회사명을 반복하지 않고 "동사"로만 지칭하는데, 계층적/시멘틱은
  이 문단만 독립적으로 봤을 때 "LG CNS"라는 이름 자체가 청크 안에 없어 놓침(50%). 문맥적 청킹은
  **모든 청크에 "이 chunk는 LG CNS 주식에 대해 분석하는 리포트의 한 부분..."이라는 맥락을
  주입**해서 이 문제를 원천 해결 — 심지어 회사명이 전혀 없는 청크(예: 마지막 청크가 애널리스트
  서명만 담고 있음)에도 맥락이 붙어 100% 회수(`chunking_showcase_lgcns_p1.md` 참고).
- **그런데 이 우위가 다른 2개 문서에는 재현되지 않음** — Construct p1/p5는 각 뉴스/불릿 항목이
  원래도 회사명을 반복해서 언급하는 스타일이라(대명사 지칭 문제 자체가 없음) 문맥적 청킹의
  이점이 없고, 오히려 fact_recall에서는 계층적/시멘틱한테 뒤짐(Construct p5: 문맥적 50% vs
  계층적/시멘틱 각 50%/75%).
- **지연은 문맥적이 거의 항상 가장 비쌈**(청크마다 컨텍스트 생성 LLM 호출이 추가로 붙으므로) —
  단, 절대적 순위는 아님(Construct p1은 시멘틱이 청크를 더 많이 만들어(11개) 추출 호출이 늘어나
  문맥적보다 오히려 더 느려짐 — 지연은 "어떤 방식이냐"보다 "청크가 몇 개 나오냐"가 더 크게 좌우).
- **계층적 청킹은 항상 청킹 자체는 거의 무료**(0.6~0.8s, YOLO+텍스트 추출뿐 LLM/임베딩 호출 없음)
  지만 recall은 문서마다 50~100%로 들쭉날쭉 — YOLO의 Section-header 오분류/중복 박스 문제([3]
  구현 중 실측, 타이틀 영역이 여러 겹치는 박스로 잡히는 등)로 가끔 의미 없는 파편 청크(예: "인터넷
  /게임" 6자짜리 청크)가 나오는 게 원인.

### [3] 종합 판정

| 항목 | 결론 |
|---|---|
| 승자 | **없음 — 문서/콘텐츠 특성에 따라 다름**. 대명사 지칭이 잦은 애널리스트 서술문에서는 문맥적이 확실히 유리, 이미 엔티티를 반복 언급하는 뉴스/불릿형 콘텐츠에서는 이점이 없고 오히려 느림 |
| 지연 | 문맥적 > 시멘틱 ≈ 계층적(단, 청크 수가 실제 지연을 더 크게 좌우) — 계층적이 청킹 구성 자체는 압도적으로 저렴 |
| 실물 산출물 | `chunks_*.json`(3개 문서 전체) + `chunking_showcase_lgcns_p1.md`(예시 발췌) |
| 사용자 결정 | 문맥적 청킹으로 고정(다음 [5]에서 지연 단축 방안 A/B 진행) |

---

## [4] 난이도 스코어 고도화(가중합) + 헤더/푸터 제거 + Boilerplate 제거 + 구두점 정규화

사용자 피드백을 그대로 반영: "2 column → MinerU는 조금 약하다"는 지적에 따라 이진 판정을
`difficulty_score = w1*columns + w2*overlap + w3*rotation + w4*font_variance + w5*figure_density`
가중합으로 고도화하고, 추가로 헤더/푸터 제거·boilerplate 제거·구두점 정규화 3가지를 구현.

### (1) 난이도 스코어 가중합 전환 — 회귀 발견·수정

`reading_order_router.py`에 3개 신호 추가:
- **rotation**: PyMuPDF `get_text("dict")`의 line.dir가 수평(1,0)이 아닌 라인의 비율(회전된 스캔본 감지)
- **font_variance**: 페이지 내 폰트 크기의 변동계수(std/mean) — 잡지/브로슈어처럼 제목·본문·캡션
  크기가 들쭉날쭉하면 커짐("레이아웃 복잡도"의 정량화)
- **figure_density**: YOLO Table+Picture 박스가 차지하는 페이지 면적 비율

가중치는 columns/overlap(각 0.30/0.25)에 더 높게 — [1]/[2]에서 유일하게 실측 검증된 신호이기
때문이고, 나머지 3개(각 0.15)는 이번에 새로 추가해 아직 미검증인 탐색적 신호라 낮게 시작.

**회귀 발견·수정**: 가중합으로 바꾼 뒤 [2]에서 검증했던 합성 2단 PDF(좌우 각 544자)를 재검증하니
**"easy"로 오판**되는 회귀 발견 — `columns` 신호가 1.0으로 최대치여도 나머지 4개 신호(rotation/
font_variance/figure_density/일부 overlap)가 전부 0에 가까우면 가중합 점수가 0.348로 threshold
0.40에 못 미침. **[1]/[2]에서 유일하게 실측 검증된 신호(material_overlaps, 본문 분량 컬럼이
실제로 나란히 겹침)를 가중합에 희석시키면 안 된다**고 판단해, 이 신호가 있으면 가중합 점수와
무관하게 항상 hard로 확정하는 override로 분리(가중합은 이 신호가 "없을 때"만 다른 레이아웃
복잡도 근거로 보조 판단). 재검증 결과 합성 2단 PDF는 다시 정확히 hard, 실제 문서 16페이지는
전부 easy(최고점 0.36, threshold 0.40 미만) 유지 확인.

| 대상 | 판정 | 최고 스코어 |
|---|---|---|
| LG CNS(6p, 전부 easy 기대) | 전부 easy | 0.3625 |
| Construct(10p, 전부 easy 기대) | 전부 easy | 0.2210 |
| 합성 2단 PDF(hard 기대) | **hard**(override) | 0.3479 |

**한계**: rotation/font_variance/figure_density 가중치는 실제 hard 문서가 없어 아직 캘리브레이션이
안 된 초기값 — 회전된 스캔본이나 브로슈어형 실제 PDF가 생기면 재검증 필요.

### (2) 헤더/푸터 제거 — `header_footer_remover.py`(신규)

좌표(상/하단 여백 8% 영역) + 반복 빈도(전체 페이지의 50% 이상에서 반복) 결합. 페이지 번호처럼
바뀌는 숫자는 `#`로 치환해 "같은 템플릿"으로 인식(`Page 4`/`Page 5`를 동일 취급).

실측 결과 — 두 PDF 모두 정확히 탐지:

| PDF | 헤더 | 푸터 |
|---|---|---|
| LG CNS | `LG CNS [#]`(5/6페이지) | `#  Research Center`(5/6페이지) |
| Construct | `건설 Weekly #.#.#`(9/10페이지) | `하나증권•#`(9/10페이지) |

`strip_headers_footers()`로 실제 페이지 텍스트에서 해당 줄 제거 검증 완료(본문 내용은 그대로,
헤더/푸터 줄만 사라짐).

### (3) Boilerplate(Compliance Notice/Disclaimer) 제거 — `boilerplate_remover.py`(신규)

사용자가 제시한 3가지 옵션(SimHash/MinHash/Sentence Embedding) 중 **Sentence Embedding 채택**
(BGE-M3, semantic_chunker에서 이미 쓰는 모델 재사용). 이유: 참고 PDF 2건이 서로 다른 증권사
(교보증권/하나증권)라 면책조항 **문구 자체가 다름**(의미는 같으나 표현이 다름) — SimHash/MinHash는
거의 동일한 문자열 반복 탐지에 강하지만 이런 패러프레이즈는 못 잡음. 문서 수가 늘어 완전히 동일한
문구가 대량 반복되는 상황이 되면 SimHash/MinHash가 계산 비용 면에서 유리해질 수 있어 코퍼스 규모가
커지면 재검토 권장(정직하게 기록).

실측 검증(LG CNS/Construct의 Compliance Notice 섹션 + 진짜 서술형 본문 23개 문단 대조):

| 지표 | 값 |
|---|---|
| 진짜 서술형 본문 오탐(false positive) | **0/23(정밀도 100%)** |
| 법적고지 문장 탐지(recall) | 10/12(83%) |

시드 문장과 표현이 크게 다른 2건(카카오톡 사칭 경고, "유가증권 보유" 문구)은 놓침 — **정밀도를
우선**한 보수적 threshold(0.62)라 실제 분석 내용을 잘못 지우는 위험은 없지만, 완전한 boilerplate
제거를 위해서는 시드 문장을 계속 보강해야 함.

### (4) 구두점 정규화 — `text_normalization.py`에 추가

줄임표("..." / "…")와 en-dash(–)/em-dash(—)를 각각 하나의 표준 표기로 통일. 실측(Construct
PDF)에서 **같은 문서 안에서도** "재개…도봉"(줄임표 문자)과 "공식화... "(마침표 3개)가 혼용됨을
확인 — 리포트마다, 심지어 같은 리포트 안에서도 표기가 뒤섞여 있어 문자열 매칭/중복 탐지/임베딩
일관성에 영향을 줄 수 있음. en/em-dash는 단어 구분자든 숫자 범위든 음수 부호든 **모든 경우에
안전하게 ASCII 하이픈(-)으로 통일 가능**(글리프만 다를 뿐 의미는 동일) — 처음엔 "음수 부호와
헷갈릴까봐" 숫자 인접 여부로 조건을 걸었다가, 애초에 ASCII 하이픈으로 이미 쓰인 음수 표기
("-15%")는 이 정규식이 아예 매칭 대상으로 삼지 않는다는 점(en/em-dash 문자 자체만 대상)을
재확인해 조건 없이 통일하도록 단순화.

### 통합 — `text_extraction.py` 업데이트

`extract_pdf_text()`에 헤더/푸터 제거(기본 켜짐, 가벼움)와 구두점 정규화(항상 적용)를 통합.
Boilerplate 제거는 임베딩 모델 로드가 필요해 상대적으로 무겁고 **문단 단위로 적용해야 의미가
있어서**(페이지 전체를 통째로 판정하면 안 됨 — 한 페이지에 서술형 본문과 법적고지가 섞여 있을
수 있음, table_processing [22]에서 "표 전체 스킵 대신 행 단위 필터"로 갔던 것과 같은 이유) 청킹
이후 문단 단위에서 호출자가 선택적으로 적용하도록 분리.

**회귀 확인**: 헤더/푸터 제거 + 구두점 정규화 적용 후 골든셋 재검증 — LG CNS(11/11, 11/11),
Construct(10/10, 16/16) 전부 100% 유지. Construct p5만 21개 중 18개로 나온 것은 실제 회귀가
아니라 골든셋 JSON이 아직 원본 "…" 표기를 그대로 갖고 있어 정규화된 "..." 출력과 문자열이
달라진 것뿐(내용 자체는 그대로 살아있음을 직접 확인) — 골든셋 비교 스크립트의 한계이지
파이프라인 버그 아님.

### [4] 종합 판정

| 항목 | 결과 |
|---|---|
| 난이도 스코어 가중합 | **구현+회귀 수정 완료** — 확증 신호(컬럼 겹침) override 유지, 3개 신호 추가는 초기 가중치(미캘리브레이션) |
| 헤더/푸터 제거 | **완료** — 좌표+반복빈도 결합, 두 PDF 전부 정확히 탐지·제거 |
| Boilerplate 제거 | **완료**(정밀도 100%, 재현율 83%) — Sentence Embedding 채택, SimHash/MinHash는 코퍼스 규모 커지면 재검토 |
| 구두점 정규화 | **완료** — 줄임표/대시 통일, 음수 표기 영향 없음 확인 |
| 프로덕션 통합 | `text_extraction.py`에 헤더/푸터+정규화 통합(boilerplate는 문단 단위 별도 호출로 분리) |

---

## [5] 세부 최적화 5건 + 문맥적 청킹 지연 단축(Qwen vs OpenAI vs Rule-based A/B)

사용자가 [3]/[4] 코드를 검토하고 준 구체적 개선 피드백 6건 전부 구현·검증. 마지막(청킹 지연 단축)이
가장 핵심 — [3]에서 문맥적 청킹으로 고정하기로 했으니, 이제 그 지연을 줄이는 게 목표.

**보안 메모**: 이 작업 중 사용자가 채팅에 실제 OpenAI API 키를 직접 붙여넣음 — 즉시 재발급/폐기를
권고했고, 이번 세션에서는 환경변수로만 일시적으로 사용하고 어떤 파일에도 저장하지 않음(작업 종료
후 저장소 전체에 키 문자열 검색해 유출 없음 확인 완료).

### (1) 난이도 라우터 — YOLO 중복 호출 제거

`reading_order_router.py`에 `cached_boxes`/`page_boxes` 파라미터 추가 — page_classification
단계가 이미 계산한 YOLO 결과를 넘기면 재추론을 건너뜀. **A/B 실측**(Construct 10페이지): 캐시
없이 1.342s vs 캐시 재사용 0.177s(**7.6배 빠름**) — 판정 결과는 완전히 동일(`route_to_mineru`,
페이지별 difficulty 전부 일치). 실제 page_classification 모듈과의 배선(orchestration)은 아직
연결 안 함 — 인터페이스(캐시 파라미터)만 준비, 두 모듈을 실제로 묶는 건 다음 단계.

### (2) 텍스트 정규화 확장 — 한국어/금융 특화 기호

`text_normalization.py`에 `normalize_symbols_and_whitespace()` 추가:
- **▲/▼(세모)**: 장식이 아니라 **의미 있는 부호**임에 주의 — 한국 금융 리포트에서 숫자 앞
  ▲/▼는 상승/하락(증가/감소)의 부호 역할(예: "▲1,200원"=+1,200원). 숫자 앞에 오면 +/-로
  변환(부호 정보 보존), 아니면 일반 불릿으로 처리. 실측: `▲1,200원`→`+1,200원`,
  `▼0.5%`→`-0.5%` 정확히 변환 확인.
- **원문자 숫자**(①②③...) → "1." "2." "3." 등 일반 표기로 변환
- **유니코드 마이너스**(− U+2212, 수학 기호) → ASCII 하이픈(-)
- **NBSP**(U+00A0) → 일반 공백
- **NFC 정규화**(`unicodedata.normalize`) 추가 — 한글 자모 분리(NFD) 현상 방지. 테스트:
  NFD로 분해된 "한글"(6글자, 자모 분리)이 정규화 후 정확히 "한글"(2글자, 완성형)로 복원됨 확인.

`text_extraction.py`에 통합 후 골든셋 재검증 — 회귀 없음(기존 [4] 결과와 동일).

### (3) Boilerplate 탐지 — 위치 필터 + Jaccard 사전 필터로 임베딩 호출 절감

`detect_boilerplate_paragraphs_fast()` 추가: (a) 위치 필터(마지막 N페이지만 검사 대상) (b)
Jaccard 유사도 사전 필터(시드 문장과 단어 집합이 크게 겹치면 임베딩 없이 즉시 확정), 애매한
것만 임베딩으로 정밀 판정.

**A/B 실측**(문서별로 정확히 분리해서 테스트 — 처음에 두 문서를 한 리스트로 합쳐서 테스트했다가
"마지막 N페이지" 기준이 서로 다른 문서의 페이지 번호를 섞어버려 LG CNS의 boilerplate가 잘못
필터링되는 회귀를 발견, 문서별로 분리해서 재검증):

| 문서 | 원본(전부 임베딩) | 최적화(위치+Jaccard) | 판정 일치 |
|---|---|---|---|
| LG CNS(22문단) | 2.561s | **0.231s(11.1배)** | 22/22(100%) |
| Construct(47문단) | 1.243s | **0.238s(5.2배)** | 47/47(100%) |

판정 결과 완전히 동일하면서 지연만 크게 줄어듦 — 최적화 채택.

### (4)/(5)/핵심: 문맥적 청킹 컨텍스트 생성 백엔드 3종 A/B — Qwen(로컬) vs OpenAI(경량 API) vs Rule-based(무료)

`contextual_chunker.py`를 백엔드 교체 가능한 구조로 리팩터링(`generate_context_qwen`/
`generate_context_openai`/`generate_context_rulebased`). Rule-based는 계층적 청킹의
section_path + 문서 제목을 템플릿 문자열로 조립(LLM 호출 없음, 사용자 제안 그대로).
[3]의 3개 테스트 문서 전체(lgcns_p1/construct_p1/construct_p5)에서 청크 경계는 동일하게 고정한
채 컨텍스트 생성 방식만 바꿔 비교(`evaluate_contextual_backends.py`). 추출 단계는 세 백엔드
전부 로컬 Qwen으로 통일(컨텍스트 생성 방식만의 순수 효과를 보기 위함).

| 문서 | 백엔드 | entity_recall | fact_recall | 컨텍스트생성 | 총지연 |
|---|---|---|---|---|---|
| LG CNS p1 | qwen | **100%** | 60% | 54.8s | 114.8s |
| | openai | 50% | 80% | 7.9s | 59.0s |
| | rulebased | 50% | 60% | 0.0s | 49.0s |
| Construct p1 | qwen | 88% | **75%** | 70.0s | 122.6s |
| | openai | 88% | 50% | 8.1s | 64.2s |
| | rulebased | 88% | 50% | 0.0s | 45.4s |
| Construct p5 | qwen | **80%** | 50% | 33.2s | 66.0s |
| | openai | 40% | 25% | 5.9s | 41.8s |
| | rulebased | 40% | **75%** | 0.0s | 31.8s |
| **평균** | **qwen** | **89.3%** | 61.7% | 52.7s | 101.1s |
| | openai | 59.3% | 51.7% | 7.3s | 55.0s |
| | rulebased | 59.3% | 61.7% | **0.0s** | **42.1s** |

**핵심 발견(예상 밖)**: OpenAI 경량 모델(gpt-4o-mini)로 바꾸면 컨텍스트 생성이 7배 빨라지지만
(52.7s→7.3s), entity_recall이 89.3%→59.3%로 같이 떨어짐 — **그런데 이 59.3%는 LLM 호출을
아예 안 하는 rule-based와 정확히 같은 수치**. 심지어 fact_recall은 rule-based(61.7%)가
openai(51.7%)보다 높음. 즉 **이 3개 문서 범위에서는 OpenAI 경량 모델이 공짜인 rule-based
대비 recall 이득이 전혀 없으면서 API 비용만 발생** — 유료 API로 바꿀 이유가 없다는 뜻.

로컬 Qwen만 유일하게 89.3% entity_recall을 달성한 이유는 [3]에서 확인한 LG CNS p1의 "동사"
대명사 문제 — Qwen은 컨텍스트를 생성할 때 매 청크마다 정확히 "LG CNS 주식에 대해 분석하는
리포트..."라고 회사명을 명시했지만(`chunking_showcase_lgcns_p1.md` 참고, 심지어 회사명이 전혀
없는 마지막 청크(애널리스트 서명만 담김)에도), OpenAI/rule-based는 이 특정 케이스에서 그 정도로
일관되게 회사명을 명시하지 못함 — **작은 로컬 VLM이 특정 태스크(문서 내 엔티티를 정확히
추적해서 매번 명시)에서 상용 경량 API보다 더 나은 경우가 실측으로 확인됨**(일반적인 직관과는
반대라 눈여겨볼 결과).

### [5] 종합 판정 및 권고

| 항목 | 결론 |
|---|---|
| YOLO 재사용(난이도 라우터) | **7.6배 지연 감소**, 판정 결과 완전 동일 — 채택 |
| 텍스트 정규화 확장(▲▼/원문자/NBSP/NFC) | **완료**, 골든셋 회귀 없음 |
| Boilerplate 탐지 최적화 | **5~11배 지연 감소**, 판정 결과 완전 동일 — 채택 |
| 문맥적 청킹 백엔드 | **로컬 Qwen 유지 권고** — OpenAI 경량 모델은 속도(1.8배)는 얻지만 recall이 rule-based 수준까지 떨어져 API 비용 대비 이득 없음. **지연을 반드시 줄여야 한다면 OpenAI가 아니라 rule-based로 전환**(entity_recall 동일 59.3%, fact_recall은 오히려 더 높음 61.7%, 지연은 2.4배 감소 101.1s→42.1s, 비용 0원) |
| 최종 권고 | recall 우선이면 로컬 Qwen 그대로, 지연 최우선이면 rule-based로 전환(OpenAI는 이 3문서 범위에서 선택할 이유가 없음) — 실제 운영 규모(문서 수·페이지 수)가 커지면 재검증 필요(지금은 3개 문서 표본) → **[6]에서 이 트레이드오프 자체가 해소됨** |

---

## [6] 최종 프로덕션 파이프라인 적용 + 텍스트 정확도 재측정

사용자 지시: "맞는 파이프라인은 적용해줘" + "텍스트 정확도에 대해서 한 번 더 측정". [5]의 A/B는
문맥적 청킹의 "기본 분할"(base_chars 그리디 누적, 문서 구조 무시)에 rule-based 컨텍스트를 붙였을
때 정적 placeholder(문서 제목 하나)만 반복돼 표현력이 약했던 것으로 재확인 — **계층적 청킹의
실제 문단 경계 + 청크마다 실제로 다른 section_path**를 rule-based 컨텍스트 생성에 그대로
넘기도록 `contextual_chunker.py`에 `chunk_contextual_production()` 추가(계층적 청킹으로 문단을
얻고, 각 문단의 진짜 section_path로 컨텍스트를 조립 — 둘 다 LLM 호출 없음, 완전 무료).

### 재측정 1: 텍스트 추출 정확도([1] 골든셋, [2]~[5] 정규화 전부 누적 적용된 최종 상태)

| PDF | 결과 |
|---|---|
| LG CNS | **22/22(100%)** |
| Construct | 44/47(93.6%) — 3건 전부 [4]에서 이미 확인한 "…"→"..." 정규화 표기 차이(골든셋이 원본 표기 그대로라 생기는 하니스 오차, 실제 내용 손실 아님). 이를 반영하면 **사실상 100%** |

→ [1]의 whole_page 베이스라인 recall 100%가 이후 4단계의 정규화·제거 로직을 전부 결합한
뒤에도 그대로 유지됨을 재확인.

### 재측정 2: 청킹 파이프라인 entity/fact recall — 프로덕션 조합이 3가지 백엔드를 전부 능가

| 방식 | entity_recall | fact_recall | 지연(평균) |
|---|---|---|---|
| Qwen(청크마다 LLM 호출) | 89.3% | 61.7% | 101.1s |
| OpenAI 경량(청크마다 API 호출) | 59.3% | 51.7% | 55.0s |
| Rule-based, 정적 placeholder([5] 격리 테스트) | 59.3% | 61.7% | 42.1s |
| **Rule-based, 계층적 청킹의 실제 section_path(이번 절 — 채택)** | **96.0%** | **68.3%** | **57.3s** |

**세 지표 전부에서 우세**: Qwen보다 recall도 높고(entity +6.7%p, fact +6.6%p) 지연도 훨씬 낮음
(101.1s→57.3s, **1.8배**). [5]의 정적 placeholder rule-based보다는 recall이 크게 개선됨
(entity +36.7%p) — 지연이 조금 늘긴 했지만(42.1s→57.3s, 계층적 청킹이 문서 구조를 더 잘게
나눠 청크 수가 늘어난 영향) 그 대가로 recall 손실이 없어짐. **[5]에서 있었던 "recall이냐
지연이냐" 트레이드오프 자체가, 정적 컨텍스트를 실제 문서 구조 기반 컨텍스트로 바꾸는 것만으로
해소됨** — LLM 호출은 여전히 0건.

**왜 이렇게 개선됐는지**: [5]의 격리 테스트에서 rule-based가 낮은 entity_recall(59.3%)을 보인
이유는 컨텍스트 생성 로직 자체의 한계가 아니라 "어떤 section_path를 넣어주느냐"의 문제였음 —
정적 문서 제목 하나만 반복하면 청크마다 차별화된 신호가 없어 도움이 적지만, 계층적 청킹이 실제로
계산한 청크별 section_path(예: 뒷부분 청크엔 "인터넷/게임 LG CNS 064400 > 투자의견 Buy 및
목표주가 89,000원 유지"까지 누적)를 쓰면 회사명이 대부분의 섹션 경로 어딘가에 들어있어 "동사"
대명사 문제가 규칙 기반만으로도 충분히 해소됨.

### [6] 최종 채택 파이프라인

```
PDF 페이지
  │
  ├─ reading_order_router: 난이도 판정(easy/hard, 가중합 스코어) → easy만 아래 진행
  │
  ├─ whole_page(PyMuPDF get_text) 추출 — [1] 검증, recall 100%
  │     └─ PUA 제거 + 헤더/푸터 제거(좌표+반복빈도) + 구두점/기호/공백 정규화 + NFC
  │
  └─ chunk_contextual_production:
        ├─ chunk_hierarchical(YOLO 구조 기반 문단 분리, section_path 포함) — LLM 호출 없음
        └─ generate_context_rulebased(청크별 실제 section_path 사용) — LLM 호출 없음
```

전체 파이프라인에 **LLM 호출이 단 한 번도 없음**(청킹 이후 실제 엔티티/사실 추출 단계에서만
Qwen 호출) — 그럼에도 청크마다 LLM이 생성한 컨텍스트를 붙였을 때(Qwen 백엔드)보다 오히려 더
높은 recall을 냄. Boilerplate 제거(문단 단위, 임베딩 필요)는 별도 호출 지점으로 분리 유지(문서
전체를 통째로 판정하면 안 되는 이유는 [4] 참고).

### [6] 종합 판정

| 항목 | 결과 |
|---|---|
| 텍스트 추출 정확도 | LG CNS 100%, Construct 100%(정규화 표기 차이 제외) — [1] 이후 모든 고도화를 거쳐도 유지 |
| 최종 채택 청킹 방식 | **`chunk_contextual_production`**(계층적 경계 + 실제 section_path 기반 rule-based 컨텍스트) |
| vs 로컬 Qwen 백엔드 | recall 더 높음(entity +6.7%p, fact +6.6%p) + 지연 1.8배 낮음 — 완전 우위 |
| vs OpenAI 경량 API | recall 훨씬 높음(entity +36.7%p) + 비용 0원 — 도입 이유 없음(폐기) |
| LLM 호출 비용 | 청킹 단계 전체 0건(YOLO+규칙 기반만 사용) |

---

## [7] 사용자 제안 검증 — 계층적 청킹에 gpt-4o-mini(SLM)를 붙이면 rule-based보다 나은가?

**질문**: [6]의 rule-based 컨텍스트 대신, 같은 계층적 청킹 경계에 gpt-4o-mini로 컨텍스트를
생성하면 더 좋아지지 않는가? — [5]의 openai 백엔드는 얕은 naive base_chars 분할에 적용했었던
반면, rule-based가 "정적 placeholder"([5])에서 "계층적 청킹의 실제 section_path"([6])로 바꿨을
때 recall이 크게 개선됐던 것과 같은 효과가 openai에도 있을 수 있다는 사용자의 합리적인 가설.

`chunk_contextual_production()`에 `backend` 파라미터를 추가해 "rulebased"/"openai"/"qwen" 전부
**같은 계층적 청킹 경계** 위에서 컨텍스트 생성 방식만 바꿔 비교 가능하게 리팩터링
(`evaluate_hierarchical_openai.py`).

| 문서 | 방식 | entity_recall | fact_recall | 지연 |
|---|---|---|---|---|
| LG CNS p1 | rule-based | 100% | 80% | 74.11s |
| | gpt-4o-mini | 100% | 80% | 94.08s |
| Construct p1 | rule-based | 88% | 75% | 62.33s |
| | gpt-4o-mini | 88% | 75% | 74.69s |
| Construct p5 | rule-based | 100% | 50% | 35.35s |
| | gpt-4o-mini | 100% | 50% | 49.25s |
| **평균** | rule-based | **96.0%** | **68.3%** | **57.3s** |
| | gpt-4o-mini | 96.0% | 68.3% | 72.7s |

**결론**: recall이 소수점까지 완전히 동일함(3문서 전부) — gpt-4o-mini를 추가해도 얻는 게 없고,
API 호출 왕복 시간만큼 지연이 27% 늘어남(57.3s→72.7s) + API 비용 발생. **계층적 청킹의
section_path 자체가 이미 하류 추출에 필요한 정보를 충분히 담고 있어서, 그 정보를 "규칙으로
조립하냐 LLM이 다시 자연어로 풀어쓰냐"는 차이를 만들지 않음** — [6]의 결론(정보의 유무가
중요하지 생성 방식은 안 중요하다)을 한 번 더 재확인.

**보안**: 이 검증에 쓴 OpenAI 키는 사용자 요청으로 `.env`에 저장(이미 `.gitignore`에 등록돼
있어 git 추적 대상 아님, 커밋 금지 지시 재확인 후 진행).

### [7] 종합 판정

| 항목 | 결론 |
|---|---|
| gpt-4o-mini + 계층적 청킹 | recall 개선 없음(rule-based와 완전 동일), 지연만 27% 증가 — **도입 이유 없음** |
| 최종 결론 | [6]의 rule-based 채택 유지가 맞음 — 이 검증으로 재확인 |

### 발견: 최종 파이프라인이 페이지당 YOLO를 두 번 호출하고 있었음

`요약.md` 작성 중 사용자 질문("욜로 두 번 쓰면 지연 늘잖아")으로 재점검 — [5]에서 검증한 "YOLO
결과 재사용시 7.6배 빠름"이 **아직 실제 파이프라인에 배선되지 않았음**을 확인. `text_extraction.
extract_pdf_text()`는 `assess_pdf()`(난이도 라우팅)를 호출할 때 `page_boxes`를 넘기지 않고,
`chunk_contextual_production()`의 `chunk_hierarchical()`도 별도로 자기 몫의 YOLO를 새로 호출함
— 페이지당 YOLO가 실제로는 두 번(라우터 1회 + 계층적 청킹 1회) 따로 호출되고 있었음. [8]에서
바로 수정.

---

## [8] YOLO 중복 호출 제거 — 실제 배선 완료

`yolo_layout.py` 신규(공유 모듈): `run_yolo_layout(model, page, page_idx)` 하나로 통일 —
`reading_order_router.py`의 자체 `_run_yolo`를 이걸 쓰도록 교체, `hierarchical_chunker.
_get_boxes_with_text()`에 `cached_boxes` 파라미터 추가(YOLO 없이 넘겨받은 박스 재사용),
`contextual_chunker.chunk_contextual_production()`도 `cached_boxes`를 그대로 통과시키도록 수정.

`text_extraction.py`에 `process_pdf(pdf_path, model, doc_title, ...)` 신규 — 페이지마다:
```
cached_boxes = run_yolo_layout(model, page, i)   # ← 여기서 딱 한 번만 호출
assess_page_difficulty(..., cached_boxes=cached_boxes)      # 난이도 판정에 재사용
chunk_contextual_production(..., cached_boxes=cached_boxes)  # 계층적 청킹에도 재사용
```

**검증**:
- `model.predict` 호출 횟수를 몽키패치로 직접 카운트 — LG CNS(6p): 정확히 6회, Construct(10p):
  정확히 10회(이전엔 각각 12회, 20회였을 것 — easy 판정된 페이지마다 청킹까지 진행하므로).
- 판정/청크 결과 완전 동일(YOLO 추론 자체가 결정적이라 같은 입력에 같은 모델을 다시 돌리면 같은
  출력 — difficulty_score, n_chunks 전부 이전 개별 호출 결과와 일치 확인).
- 골든셋 텍스트 추출 recall 재검증: LG CNS 22/22, Construct 44/47(기존과 동일, 회귀 없음).
- **문서 전체 기준 실측 지연**: Construct(10페이지) 기준 2.735s(중복 호출) → 1.881s(통합) —
  **1.45배**. [5]에서 측정한 "1.342s→0.177s(7.6배)"는 YOLO 호출 자체만 격리해서 잰 수치라 더
  컸고, 문서 전체(텍스트 추출·정제·청킹 등 YOLO와 무관한 비용까지 포함) 기준으로는 1.45배가
  정직한 실측치 — 두 수치가 다른 건 모순이 아니라 "무엇을 분모로 재는가"의 차이.

### [8] 종합 판정

| 항목 | 결과 |
|---|---|
| YOLO 중복 호출 | **제거 완료** — `process_pdf()`가 페이지당 1회만 호출, 난이도 판정+계층적 청킹 양쪽에 재사용 |
| 실측 개선(문서 전체 기준) | 1.45배(Construct 10p: 2.735s→1.881s) |
| 회귀 검증 | 판정 결과·청크 수·골든셋 recall 전부 이전과 동일 |
| 남은 범위 | page_classification 모듈 자체와의 YOLO 결과 공유는 아직 — text_processing 내부(라우터+청킹) 통합만 완료, 그 앞단(페이지 분류)까지 묶으려면 추가 배선 필요 |

---

## [9] 임베딩 모델 3종 비교 — BGE-M3 vs dragonkue/BGE-m3-ko vs OpenAI text-embedding-3-small

청킹까지 완료된 뒤 다음 단계(인덱싱)로 넘어가기 전, 실제 임베딩할 모델을 정해야 함. 사용자
요청대로 Claude가 직접 검색 정답셋을 만들고(표준 IR 평가 방식) 3개 후보를 비교.

**후보 선정**: BGE-M3(다국어 베이스, 이미 시멘틱청킹/boilerplate탐지에서 쓰고 있음),
`dragonkue/BGE-m3-ko`(HuggingFace 검색 결과 커뮤니티 한국어 BGE-M3 파인튜닝 중 압도적으로
많이 쓰이는 모델, 다운로드 49만+회 — `upskyy/bge-m3-korean`(3.6만) 등 후보 중 최다), OpenAI
`text-embedding-3-small`(API).

**평가 방법**: [6]/[8]에서 검증된 최종 파이프라인(`chunk_contextual_production`)으로 3개 문서
(lgcns_p1/construct_p1/construct_p5)의 실제 청크 21개를 코퍼스로 구성, Claude가 자연스러운
한국어 질의 15개를 작성(정답 청크는 청크 텍스트 안의 고유 부분문자열로 식별) — 각 모델로
코퍼스+질의를 임베딩한 뒤 코사인 유사도로 순위를 매겨 Recall@1/Recall@3/MRR 측정.

**구현 중 발견한 버그**: 초기 실행에서 질의 15개 중 3개의 정답 청크를 못 찾는 문제 발견 — 원인은
정답 판정을 `raw_chunk`(청크 본문만)로 했던 것. 그런데 뉴스 헤드라인 같은 Section-header 텍스트는
[8]의 계층적 청킹 설계상 본문(`raw_chunk`)에는 안 들어가고 section_path 메타데이터로만 남아
**컨텍스트 접두어**(`text` 필드, rule-based로 생성됨)에만 존재함(예: "120조 투자"라는 수치가
헤드라인에만 있고 본문 문장에는 없었음). 실제로 임베딩되는 건 컨텍스트 접두어까지 포함한
`text` 필드이므로, 정답 판정 기준을 `raw_chunk`→`text`로 수정 — **오히려 [6]/[8]에서 검증한
"rule-based 컨텍스트 주입이 대명사/헤드라인 정보를 보존한다"는 결론을 한 번 더 재확인한 계기**
(나머지 1건은 단순 오탈자성 앵커 문구 수정).

### 결과(코퍼스 21청크, 질의 15개)

| 모델 | Recall@1 | Recall@3 | MRR | 코퍼스 임베딩(21청크) |
|---|---|---|---|---|
| BGE-M3(다국어 베이스) | 87%(13/15) | 93%(14/15) | 0.907 | 0.855s |
| **dragonkue/BGE-m3-ko(채택)** | 87%(13/15) | **100%(15/15)** | **0.922** | **0.738s(최속)** |
| OpenAI text-embedding-3-small | 87%(13/15) | 93%(14/15) | 0.911 | 1.305s(API 왕복 포함) |

**결론**: Recall@1은 3종 전부 동률이지만, **BGE-m3-ko만 유일하게 Recall@3 100%**(정답이 항상
top-3 안에 들어옴 — 다른 두 모델은 각각 1개 질의에서 정답이 top-3 밖으로 밀림) + 가장 높은
MRR + 가장 빠른 임베딩 속도. 세 지표 전부에서 우세하거나 최소 동률이라 트레이드오프 없이 명확한
채택 — 한국어 금융 도메인 텍스트에 커뮤니티 파인튜닝이 실제로 유효했음을 확인.

`embedding.py` 신규 — `dragonkue/BGE-m3-ko`를 기본 임베딩 모델로 노출(싱글턴 로드, 코사인
유사도용 L2 정규화 임베딩 반환).

### [9] 종합 판정

| 항목 | 결과 |
|---|---|
| 채택 임베딩 모델 | **dragonkue/BGE-m3-ko** — Recall@3 100%, MRR 0.922(최고), 임베딩 속도 최속 |
| vs BGE-M3(베이스) | Recall@3 +7%p, MRR +0.015, 속도도 근소 우위 — 커뮤니티 한국어 파인튜닝이 실제로 유효 |
| vs OpenAI 경량 임베딩 | Recall@3 +7%p, MRR +0.011, API 비용/왕복지연 없음 — 로컬 모델이 더 나음 |
| 평가 방법 | 표준 IR 지표(Recall@1/@3, MRR), Claude가 실제 최종 파이프라인 산출물로 골든셋 작성 |
| 다음 단계 | 벡터DB(chromadb 등) 인덱싱 + BM25 하이브리드 검색은 아직 미구현 — 사용자 확인 후 진행 |

---

## [10] 사용자 리뷰 피드백 2건 수정 — Boilerplate 제거 배선 + page_classification과의 YOLO 공유

[9] 완료 후 사용자에게 오늘 작업 리뷰를 요청받아 점검하는 과정에서, 직접 짚은 문제 2건을 그
자리에서 수정.

### (1) Boilerplate 제거를 `process_pdf()`에 배선

[4]/[5]에서 구현한 `detect_boilerplate_paragraphs_fast()`가 여태 **호출자가 수동으로 불러야만
적용되는 독립 함수**였음 — 인덱싱 스크립트 작성자가 이 호출을 빠뜨리면 Compliance Notice
문구가 그대로 임베딩되는 위험이 실측 전에 미리 지적됨. `process_pdf(remove_boilerplate=True`
기본값`)`에서 각 페이지의 청크가 나온 뒤 자동으로 boilerplate 판정 + 제거하도록 배선. 임베딩
모델은 [9]에서 채택한 `embedding.get_embedding_model()`(BGE-m3-ko)을 그대로 재사용(인덱싱용
모델과 같아서 별도 로드 비용 없음).

구현 중 위치 필터 버그 발견·수정: `detect_boilerplate_paragraphs_fast`의 `last_n_pages_only`는
"문서 전체를 한 번에 배치 처리"한다는 전제로 `max(paragraph_pages)`를 계산하는데, `process_pdf()`
안에서 페이지를 한 장씩 순회하며 호출하면 그때마다 `paragraph_pages`가 그 페이지 번호 하나만
반복돼 "마지막 N페이지" 계산 자체가 깨짐 — 페이지 단위 게이팅(마지막 N페이지 안에 있는지)은
`process_pdf()`가 직접 계산하고, 함수 자체는 위치 필터 없이 그 페이지의 청크에만 호출하도록 수정.

**검증**: LG CNS p6(Compliance Notice 페이지) 청크 9개 → 4개 제거(5개 남음), p1/p4(진짜 본문)는
11개/1개 그대로 — 이전 [4] 개별 테스트에서 확인했던 정밀도 100%/재현율 83% 결과와 정확히 일치.
Construct p10도 7개 → 4개(3건 제거)로 일관된 동작 확인.

### (2) page_classification과 text_processing 간 YOLO 중복 제거

[8]은 text_processing **내부**(난이도 라우터 + 계층적 청킹)만 통합했고, page_classification
모듈 자체는 여전히 별도로 자기 몫의 YOLO를 돌리고 있었음(사용자가 정확히 이 gap을 지적).
`yolo_layout.py`를 `text_processing/`에서 `pdf_pipeline/`(두 모듈의 공통 상위 디렉터리)로
이동해 두 모듈이 같은 공유 유틸을 참조하도록 하고, `page_classification/page_classifier.py`
신규(YOLOv11n 기반 분류를 재사용 가능한 함수로 노출, `cached_boxes` 반환) + `text_extraction.
process_pdf()`에 `page_boxes` 파라미터 추가(페이지 단위로 미리 계산된 박스를 넘기면 재추론 생략).

**검증**: `model.predict` 호출을 몽키패치로 카운트 — `page_classification.classify_pdf()` 호출
후 10회(Construct 10페이지), 그 결과를 `page_boxes`로 넘겨 `text_extraction.process_pdf()`를
호출해도 **여전히 10회**(추가 호출 0건) — 파이프라인 전체(분류+텍스트처리) 기준으로 페이지당
YOLO가 정확히 1번만 호출됨을 확인. 판정/청크 결과도 이전과 동일.

### [10] 종합 판정

| 항목 | 결과 |
|---|---|
| Boilerplate 제거 배선 | **완료** — `process_pdf()` 기본 동작에 포함, 위치필터 버그 발견·수정, 회귀 없음 |
| page_classification ↔ text_processing YOLO 공유 | **완료** — `yolo_layout.py` 공유 위치 이동 + `page_classifier.py` 신규 + `page_boxes` 파라미터, 파이프라인 전체 기준 페이지당 YOLO 1회 확인 |
| 남은 범위 | table_processing 쪽 YOLO 호출(Adaptive Router)은 아직 이 공유 체계에 안 묶임 — 표 처리까지 포함해 페이지당 YOLO 완전히 1회로 만들려면 추가 통합 필요 |

---

## [11] 텍스트 라우팅 끝에 구조화 출력(Structured Output) 도입

사용자 요청: 텍스트/표 각 라우팅이 끝나는 지점에 LLM 구조화 출력을 붙이고, 추출할 메타데이터
초안은 우선 이쪽에서 틀을 잡고 사용자가 필드를 가감. 백엔드는 명시적으로 "open api 사용할 것"
(OpenAI API) 지정 — [5]/[7]에서 컨텍스트 생성용으로 이미 검증된 gpt-4o-mini + `OPENAI_API_KEY`
관례를 그대로 재사용.

**설계 원칙**: rule-based로 이미 안정적으로 뽑히는 것(이 파이프라인의 section_path, table_processing의
canonical_field/numeric_value/unit)은 LLM에 다시 시키지 않는다 — LLM은 자유 텍스트 이해가 필요한
것(엔티티/논조/요약)만 담당. 신규 공유 모듈 `pdf_pipeline/structured_output.py`(text_processing/
table_processing 양쪽이 재사용) + OpenAI Structured Outputs(`chat.completions.parse(response_format=
Pydantic 모델)`, strict 모드)로 구현.

**텍스트 청크 메타데이터 초안 스키마**(`TextChunkMetadata`, 사용자가 가감 예정):
`entities`(언급 기업/기관), `sector_mentioned`, `topic`(1줄), `metric_mentions`(지표명만, 값은 안 뽑음
— rule-based 영역과 중복 방지), `time_period`, `sentiment`(positive/neutral/negative), `contains_
forward_looking_statement`, `summary`(1문장).

**배선 위치**: `process_pdf()` — 페이지당 chunk가 다 만들어지고(계층적 청킹 + 컨텍스트 주입 +
boilerplate 제거까지 끝난) 직후, 그 페이지의 전체 chunk를 **한 번의 API 호출**로 배치 처리
(`extract_text_chunk_metadata`, chunk마다 호출하면 API 호출 수가 페이지당 청크 수만큼 늘어나서
비효율 — chunk_index로 순서를 명시시켜 매칭하므로 LLM이 순서를 안 지켜도 안전). 새 파라미터
`add_structured_metadata`(기본 **False**, 유료 API라 명시적으로 켜야 함) + `openai_client`(재사용용).

**검증**: 실제 LG CNS 발췌 2개 chunk로 라이브 스모크 테스트 — entities/sector_mentioned/sentiment/
time_period 모두 합리적으로 채워짐 확인(예: "투자의견 Buy 유지, 2026년 EPS 성장" chunk →
`sentiment=positive`, `contains_forward_looking_statement=true`, `time_period="2026E"`). 정식
정확도 평가([9]류 golden set 대조)는 아직 안 함 — 이 스키마 자체가 초안이라 필드가 확정되면
그때 평가할 것.

### [11] 종합 판정

| 항목 | 결과 |
|---|---|
| 백엔드 | OpenAI gpt-4o-mini, Structured Outputs(`chat.completions.parse`, strict) |
| 배선 위치 | `process_pdf()` — 페이지당 1회 호출, chunk 배열 배치 처리 |
| 기본값 | `add_structured_metadata=False`(opt-in, 유료 API 비용 때문) |
| 스키마 상태 | 초안 — 사용자가 필드 가감 예정, 정식 정확도 평가는 스키마 확정 후 진행 |

---

## [29] 구조화 출력 병렬화(concurrent.futures)

사용자 지적("병목 없는거야?") 반영: `[11]`/`[25]`에서 배선한 구조화 출력이 페이지/표마다
**순차** API 호출이라 실측 시 작은 문서(6~10페이지)도 처리 시간이 20~30배 늘어나는 게 확인됨.
로컬 연산(YOLO/청킹/표 파싱)을 전부 끝낸 뒤 API 호출만 마지막에 `ThreadPoolExecutor`(I/O
바운드라 스레드로 충분, `max_workers=8`)로 한꺼번에 병렬 디스패치하도록 `process_pdf()`/
`build_records()` 둘 다 수정. 재측정 결과: LGCNS 텍스트 +23.79s→**+14.59s**, 표 +25.42s(표당
1.96s)→**+3.95s(표당 0.30s)**, Construct도 유사(표 기준 6~8배 단축). LGCNS/Construct 재검증
결과 회귀 없음(recall/hit_rate 전부 동일). 상세 아키텍처/추가 설계는
`pdf_pipeline/실험_생성단계_아키텍처설계.md` 참고.

---

## [30] "hard 페이지 = 정말 리딩오더 복원이 필요한 페이지인가?" — 전용 모델(LayoutReader)로 검증

사용자 질문: hard로 분류된 페이지가 실제로 리딩오더 복원이 필요한지, [2]/[4]의 가중합 룰베이스가
적절한지, 리딩오더 판별 전용 모델을 쓸 수 있는지 검토. K-Wave PDF(73페이지) 대상.
스크립트: `pdf_pipeline/evaluate_reading_order.py`.

**모델 조사 결과**: Docling은 자체 GitHub 이슈에서 다중 컬럼 리딩오더 복원이 아직 불안정하다고
공식 인정(#1203 "Convoluted Reading Flow for Multi-Column PDFs", #2067, #3198, Discussion #2791)
— 비교 대상에서 제외. 대신 **LayoutReader**(Microsoft, LayoutLMv3 기반, ReadingBank 50만 문서로
사전학습, MinerU 등이 실제로 채택한 모델)가 HuggingFace `hantian/layoutreader`(CC-BY-NC-SA-4.0,
비상업 라이선스 — 상업 적용 시 별도 확인 필요)에 실제로 존재해 다운로드해 적용(64ms/페이지, 아주
빠름).

**방법론**: LayoutReader가 예측한 순서와 원본 PyMuPDF 추출 순서 사이의 정규화된 역전쌍 비율
(normalized Kendall-tau distance)을 계산 — 이 값이 임계치(0.15) 이상이면 "실제로 리딩오더 복원이
필요한 페이지"로 GT 라벨링(LayoutReader 자체를 전용 모델로 신뢰). 우리 rule-based hard/easy 판정을
이 GT 대비 채점.

### 검증 중 발견한 별개의 버그 — 수정 완료

K-Wave 페이지 다수(초기 40개)가 텍스트 블록 2~3개뿐인 이상 패턴을 보여 원인을 추적한 결과:
`assess_page_difficulty()`가 YOLO Table/Picture 박스를 "블록 중심점이 그 박스 안에 있는가"로만
제외했는데, PyMuPDF가 **나란히 붙은 두 YOLO Table 박스**(예: 재무상태표+손익계산서가 별개 박스로
검출된 표)의 내용을 **하나의 거대한 텍스트 블록**으로 합쳐 반환하면, 그 블록의 중심점이 두 Table
박스 "사이 틈"에 떨어져 어느 쪽 박스에도 안 걸리는 경우를 실측으로 확인(page31/35 등). 결과적으로
표 전체가 "텍스트 블록"으로 잘못 남아 난이도 판정을 오염시킴 — `reading_order_router.py`에
`_is_excluded()`(중심점 대신 exclude_rects 대비 면적 겹침 비율 50% 초과 시 제외)로 교체해 수정.
LGCNS/Construct 재검증 결과 회귀 없음 확인(recall 100%/100% 그대로, 표 227/215행·hit_rate
11.9%/4.2% 그대로).

### 성능 지표 — 층화 분석이 필요했던 이유

전체(73페이지) 기준으로는 Precision=0.971, **Recall=0.478**, F1=0.641로 재현율이 낮게 나오는데,
텍스트 블록 수로 층화하면 완전히 다른 그림이 나온다:

| 구간 | 페이지 수 | Precision | Recall | F1 |
|---|---|---|---|---|
| 전체 | 73 | 0.971 | 0.478 | 0.641 |
| n_text_blocks < 10(헤더+표+푸터 지배, "리딩오더"가 사실상 의미 약함) | 40 | 1.0 | 0.297 | 0.458 |
| **n_text_blocks ≥ 10(진짜 서술형 다컬럼 후보)** | **33** | **0.957** | **0.688** | **0.80** |

**n_blocks<10 구간의 낮은 재현율은 오해하기 쉽다** — 이 구간은 [30] 위에서 고친 버그가 없었어도
"표가 대부분이고 남은 텍스트는 헤더/제목/푸터 2~4개뿐"인 페이지들이라, 그 2~4개 블록의 순서가
뒤바뀌어도(예: 푸터가 헤더보다 먼저 추출됨) 실질적 정보 손실은 거의 없음(중요 내용인 재무제표는
table_processing이 별도로 처리). 즉 이 구간의 "GT=복원 필요" 라벨 다수는 통계적으로는 맞지만
실질적 중요도는 낮다 — 정규화된 역전쌍 비율이 블록 수가 적을수록(n=2~3) 노이즈에 민감해지는 것도
한몫한다(예: 블록 2개면 단 1번의 순서 뒤바뀜만으로도 divergence=1.0).

**n_blocks≥10 구간(진짜 다컬럼 서술형 콘텐츠)이 실질적으로 중요한 지표** — 여기서는 **F1=0.80,
Precision=0.957**로 현재 룰베이스가 꽤 잘 작동한다는 뜻. 즉 "[2]/[4]의 가중합 로직이 적절한가"에
대한 답은 **"진짜 다컬럼 서술형 텍스트에는 적절하다"**.

### 구체적으로 발견된 두 가지 실패 사례

1. **FP 1건(page3)**: `material_overlaps`가 3개 컬럼이 나란히 겹친다고 올바르게 감지해 hard로
   판정했지만, 실측 결과 PyMuPDF의 원본 추출 순서가 **이미 컬럼별로 그룹화되어 있어서**(1번
   컬럼 전체 → 2번 컬럼 전체 → 3번 컬럼 전체 순, 제목 하나만 위치가 어긋남) divergence가 낮음
   (0.0964). **"컬럼이 나란히 겹친다" ≠ "추출 순서가 실제로 깨졌다"**라는 걸 실측으로 확인 — 현재
   룰의 암묵적 가정("겹치는 컬럼 = 항상 순서 깨짐")이 항상 성립하진 않는다.
2. **FN 9건(page28/32/40/44/48/53/57/61/65, 전부 19~20블록)**: 반복되는 페이지 템플릿(엔터사별
   분석 페이지로 추정)이 일관되게 가중합 점수 0.29~0.30으로 threshold(0.40) 바로 밑에서 걸림 —
   LayoutReader는 이 템플릿에 대해 일관되게 divergence≈0.27(복원 필요)로 판단. 우연한 개별 사례가
   아니라 **이 문서의 특정 레이아웃 템플릿 전체가 threshold 바로 아래 깔려있다**는 뜻 — 재캘리브레이션
   후보로 구체적으로 지목 가능(가중치 조정 또는 hard_threshold를 0.40→0.28 근처로 낮추는 안 검토 가치 있음,
   단 LGCNS/Construct 등 기존 검증 문서에 회귀 없는지 재확인 필요).

### [30] 종합 판정

| 항목 | 결과 |
|---|---|
| 별개로 발견·수정한 버그 | 인접 Table 박스 사이 틈에 중심점이 떨어지는 텍스트 블록 제외 실패 — `_is_excluded()`로 교체, 회귀 없음 확인 |
| 리딩오더 판별 모델 존재 여부 | **있음** — LayoutReader(`hantian/layoutreader`), 64ms/페이지로 실사용 가능, Docling은 검토 후 기각(공식 이슈로 확인된 한계) |
| 룰베이스 적절성(진짜 다컬럼 텍스트, 33페이지) | **적절함** — F1=0.80, Precision=0.957 |
| 룰베이스 적절성(표 지배 페이지, 40페이지) | 지표상 낮으나(F1=0.458) 실질적 중요도는 낮음(핵심 내용은 표로 이미 처리됨) |
| 구체적 개선 여지 | (a) "컬럼 겹침=순서깨짐" 가정 재검토(page3류 FP), (b) hard_threshold 재캘리브레이션(9페이지 템플릿이 0.29~0.30에 몰림) |
| 다음 단계 제안 | LayoutReader를 hard/easy 이진 라우터 대신 **직접 리딩오더 복원기**로 승격하는 안 검토 가치 있음(MinerU 위임 없이 우리 파이프라인 안에서 64ms/페이지로 즉시 복원 가능) — 단 정확도(BLEU 등) 자체 재검증은 별도 진행 필요 |

### 추가 검증: threshold 재캘리브레이션 시도 → 안전하지 않아 기각

위 9페이지 템플릿(K-Wave, score 0.276~0.298)을 잡으려고 `hard_threshold`를 0.40에서 그 구간
근처(예: 0.35)로 낮추는 걸 실제로 검토했다 — K-Wave의 n_blocks≥10 페이지들만 보면 0.298과
0.408 사이에 뚜렷한 빈 구간이 있어 threshold를 그 사이 아무 값으로나 낮추면 이 9페이지를 깔끔히
잡을 수 있어 보였다. **하지만 LGCNS/Construct 페이지의 실제 점수를 재측정해보니 LGCNS page1
(0.3519)과 page4(0.3625)가 threshold 0.35 근처에서 걸린다** — 이 두 페이지는 이미 [1]/[6]에서
recall 100%로 실측 검증된, 실제로는 리딩오더 문제가 전혀 없는 페이지다. K-Wave 특유의 반복
템플릿을 잡으려고 threshold를 낮추면 LGCNS의 정상 페이지가 오탐으로 hard 처리되어(청킹 자체가
스킵됨) **실제 회귀**가 발생한다.

**결론**: 가중합 난이도 스코어는 문서마다 절대값 스케일이 다르다(K-Wave에서 "위험한" 0.29와
LGCNS에서 "안전한" 0.35가 실질 의미상 뒤바뀜) — threshold 하나를 손으로 조정하는 건 안전하지
않다고 판단해 **적용하지 않음**(변경 없이 0.40 유지). 이건 rotation/font_variance/figure_density
가중치가 "아직 실측 캘리브레이션이 안 된 초기값"이라고 [4]에서 이미 정직하게 기록해둔 한계가
실제 데이터로 확인된 사례 — 여러 문서를 아우르는 재보정 데이터셋 없이 임계값만 만지는 건
위험하다. 대신 이미 위에서 제안한 "LayoutReader를 직접 복원기로 승격" 쪽이 더 안전한 다음
단계로 보임(임계값 튜닝이라는 불안정한 중간 단계를 아예 건너뛸 수 있어서).

---

## [32] "5초 내 텍스트 처리" 병목 실측 프로파일링 — 원인 특정 + 수정

사용자 지적("나머지는 전부 병목 해결과 개선해줘") 반영. K-Wave(73페이지) `process_pdf()`가
11.0초 걸린다고 [실험_생성단계_아키텍처설계.md]에 기록했었는데, cProfile로 정확히 어디서
시간이 가는지 재측정.

**1차 발견 — 이건 버그가 아니라 측정 방식 문제**: 11.0초 중 **3.99초는 BGE-m3-ko 임베딩 모델의
1회성 콜드 로드**였다(`embed_model=None`으로 호출하면 `process_pdf()` 내부에서 최초 1회 로드).
실제 서버 프로세스라면 이 로드는 프로세스 시작 시 한 번만 발생하고 이후 요청부터는 재사용되므로,
"문서 1개당 처리 시간"으로 보면 원래도 6.6초가 맞는 수치였음(11.0초는 "매번 새 프로세스로 콜드
스타트"를 가정한 과도하게 비관적인 측정이었음을 재확인).

**2차 발견 — 실제 버그, 수정함**: cProfile 결과 `detect_boilerplate_paragraphs_fast`가 페이지당
(K-Wave 기준 14회) 호출되는데, 매번 고정된 7개 시드 문장(`SEED_BOILERPLATE_SENTENCES`)을
**다시 인코딩**하고 있었다 — 시드는 상수인데도 캐싱 없이 매 호출마다 재계산. `boilerplate_remover.py`에
`_get_seed_embeddings()`(embed_model+seeds 조합별 프로세스 내 캐시)를 추가해 수정.

**3차 확인 — threading은 효과 없음(실측)**: `chunk_hierarchical`의 `get_textbox()` 호출(K-Wave
기준 223회, 3.0초, 전체의 45%)을 `ThreadPoolExecutor`로 병렬화해봤으나 **속도 개선 거의 0%**
(순차 2.42s vs 4워커 병렬 2.40s, 1.01배) — PyMuPDF의 이 C 확장 호출이 GIL을 안 놓는다는 뜻.
진짜 병렬화하려면 멀티프로세싱이 필요한데, YOLO 모델을 워커마다 새로 로드해야 하는 비용 대비
남은 이득이 제한적(전체 6.6초 중 3.0초 구간만 병렬화 가능, 워커 로딩 비용과 상쇄)이라 **이번엔
구현하지 않음**(정확성 검증 없이 프로세스 구조를 바꾸는 리스크 대비 이득이 애매해서 — 사용자
부재 중 검증 못 할 변경은 보수적으로 접근).

**최종 결과**(seed 캐싱만 적용, embed_model은 서버처럼 사전 로드된 상태로 측정):

| | 수정 전 | 수정 후 |
|---|---|---|
| K-Wave(73p) `process_pdf()` | 6.61s | **5.02~5.37s** |

73페이지 문서 기준 5초 근처까지 줄었음(완전히 5초 미만은 아니지만 실질적으로 목표에 근접).
LGCNS/Construct 재검증 결과 recall/청크수/hard페이지 전부 동일 — 회귀 없음.

**추가로 구현함 — `process_pdf_streaming()`**: "문서 전체 완료"가 아니라 "페이지 단위로 끝나는
대로 바로 검색 가능"하게 만드는 제너레이터 버전을 `text_extraction.py`에 추가. `process_pdf()`와
로직은 동일(구조화 출력만 제외 — 원래도 별도 느린 레인이라 스트리밍 경로엔 안 넣음), 페이지가
끝나는 즉시 `yield`해서 호출자가 그 페이지를 바로 임베딩+벡터DB insert할 수 있게 함.

**검증**(K-Wave 73페이지): `process_pdf()`(배치) 대비 페이지별 text/difficulty/chunks 개수
**완전 일치**(불일치 0건) — 로직 동일함 확인. **첫 페이지까지 302ms** — 73페이지 문서에서도
"5초 내"는커녕 1초도 안 걸려 첫 페이지가 검색 가능해짐. "대형 문서는 5초를 못 맞춘다"는 문제를
"전체 완료 시간"이 아니라 "첫 결과까지의 시간"으로 목표를 재정의해서 실질적으로 해결.

**남은 레버(구현 안 함, 기록만)**: 멀티프로세싱 페이지 병렬화(위 이유로 보류) — 스트리밍으로
체감 지연 문제는 해결됐다고 판단해 우선순위 낮춤.

### [32] 종합 판정

| 항목 | 결과 |
|---|---|
| 실제 버그 | boilerplate 시드 문장 재인코딩 낭비 — `_get_seed_embeddings()` 캐싱으로 수정 |
| threshold 재캘리브레이션 | 시도했으나 문서 간 스케일 불일치로 위험 판단, **미적용**(위 리딩오더 절 참고) |
| threading 병렬화 | 실측 결과 무효(PyMuPDF C콜이 GIL 유지) — 시도 안 함이 아니라 **시도 후 기각** |
| K-Wave 개선 | 6.61s → 5.02~5.37s(warm 기준), 회귀 없음 |

---

## [33] 추가 병목 스캔(텍스트/표/페이지분류 3개 파이프라인 전체) — 공유 유틸의 디스크 왕복 제거

사용자 지시("또 병목 찾아서 해결해줘. 텍스트, 테이블, 페이지 분류 파이프라인 내에서") 반영,
세 파이프라인을 cProfile로 각각 재스캔.

**공유 버그(가장 큰 레버) — `pdf_pipeline/yolo_layout.py`의 `run_yolo_layout()`**: 페이지를
렌더링한 뒤 **PNG로 디스크에 저장했다가 곧바로 다시 읽어들이는** 왕복이 있었음(인코딩+write+
read+디코딩). `pix.samples`(렌더링 결과의 원본 RGB 바이트)를 `Image.frombytes()`로 바로 PIL
이미지로 변환하도록 교체 — 픽셀 단위로 완전히 동일한 결과임을 numpy로 직접 검증(`np.array_equal`
True), 실측 50회 기준 21.9ms/회 → 0.9ms/회(**약 25배**). 이 함수는 page_classification/
text_processing/table_processing **셋 다 공유**하는 유틸이라 여기 한 곳만 고쳐도 세 파이프라인
전부에 적용됨 — K-Wave(73페이지) `classify_pdf()` 기준 **7.71s → 5.09s**(34% 단축).

표 처리 쪽 추가 발견·수정은 `table_processing/실험.md [30]` 참고(표 셀 파싱이 훨씬 더 큰
병목이었음 — 별도 기록). LGCNS/Construct 전체 파이프라인 재검증 결과 recall/hit_rate/청크수
전부 동일 — 회귀 없음.

### [33] 종합 판정

| 항목 | 결과 |
|---|---|
| 발견한 버그 | `run_yolo_layout()`의 불필요한 PNG 디스크 왕복 — 세 파이프라인이 공유하는 함수라 영향 범위 큼 |
| 수정 | `Image.frombytes()`로 인메모리 변환, 픽셀 동일성 검증 완료 |
| 효과 | 이미지 변환 자체 25배, K-Wave page_classification 34% 단축 |
| 회귀 | 없음(LGCNS/Construct recall 100%/100%, 표 227/215행 그대로) |

---

## [34] "hard 페이지가 진짜 리딩오더가 필요한가" — 클로드 전수 검토 기반 재검증

사용자 요청: `[30]`에서 LayoutReader의 divergence 신호를 GT로 삼아 룰베이스를 평가했는데, 이번엔
**LayoutReader 대신 클로드가 직접 정답을 판정**해서 다시 비교. K-Wave 73페이지 **전수**(hard 34개
전부 + easy 39개 중 대다수)를 whole_page 원문으로 직접 읽고, "추출 순서 때문에 숫자가 엉뚱한
라벨에 붙거나 서로 다른 회사/주제 문장이 섞이는 등 RAG/LLM 소비 관점에서 실질적 의미 훼손이
있는가"를 기준으로 판정(순수 타이포그래피적 순서 완벽성이 아니라 실용적 기준). 골든셋:
`ground_truth_reading_order_kwave.json`.

**결과: 73페이지 중 리딩오더 복원이 실질적으로 필요한 페이지는 0개.** 관찰된 6개 반복 패턴
(재무제표 테이블, 분기 실적 테이블, "4개 차트/페이지" 템플릿, 번호·대시 서술 불릿, Stock Data
2단 박스, TOC/투자의견이력/Compliance) 전부 — 컬럼이 여러 개로 감지되어도 추출 순서가 **컬럼별로
그룹화**되어 있거나 **라벨→값 순서가 일관**되어 있어서, 사람이 읽어도(또는 LLM이 읽어도) 혼동될
지점이 없었음. 유일한 진짜 다컬럼 서술형 페이지(page3, 3단 "이슈 요약" 박스)조차 컬럼별로 온전히
그룹화되어 추출됐고, "Summary" 제목 하나만 위치가 어긋난 정도라 최종 false로 판정.

**정량 비교** (전체 73페이지, precision = TP/(TP+FP), GT positive가 0이라 recall은 정의 불가):

| 방식 | Hard/필요 판정 수 | TP | FP | Precision | Accuracy |
|---|---|---|---|---|---|
| 룰베이스(가중합+material_overlaps) | 34/73 | 0 | 34 | **0%** | 53.4% |
| LayoutReader(divergence≥0.15, `[30]`) | 69/73 | 0 | 69 | **0%** | 5.5% |

**해석**: 이 문서(K-Wave, 차트/표 중심 산업 리포트)에 대해서는 두 방식 다 precision 0%지만,
**룰베이스가 LayoutReader의 divergence 신호보다 훨씬 덜 과다판정**함(34 vs 69, accuracy 53.4%
vs 5.5%) — `[30]`에서 "LayoutReader를 직접 복원기로 승격"을 제안했었는데, 이번 결과는 그 반대
방향을 시사함: **divergence를 hard/easy 판별 신호로 그대로 쓰는 건 이 문서 유형에 안 맞다.**
"컬럼이 겹친다"/"원본 순서와 다르다"는 신호 자체가, 이 문서의 지배적 레이아웃(정형화된 정보박스,
차트 템플릿)에서는 "의미 훼손"과 상관관계가 약하기 때문 — LayoutReader가 학습한 ReadingBank
(일반 문서 50만 건)의 "이상적 읽기 순서" 기준과, 증권사 리포트 특유의 구조화된 박스형 레이아웃의
"실질적으로 문제없는 순서" 기준이 다르다는 뜻으로 해석됨.

**한계(정직하게 기록)**: (1) 검토자가 클로드 1명, 재현/교차검증 없음 — 판정 기준을 명시했지만
주관이 개입될 수 있음. (2) 문서 1건(K-Wave) 기준 — 이 결론이 다른 레이아웃 스타일(예: 진짜
2단 잡지형 기사)에도 일반화되는지는 확인 안 됨(LGCNS/Construct는애초에 hard 페이지가 0개라 이
비교 자체가 불가능했음). (3) 이미지 렌더링 없이 텍스트만으로 판정 — 표/차트의 "시각적" 리딩오더
문제(예: 이미지 자체를 못 보면 판단 못하는 경우)는 반영 안 됐을 수 있음.

### [34] 종합 판정

| 항목 | 결과 |
|---|---|
| GT 방식 | LayoutReader divergence(자동) → 클로드 전수 검토(수동)로 교체 |
| 결과 | K-Wave 73페이지 중 리딩오더 복원 실제로 필요한 페이지 **0개** |
| 룰베이스 precision | 0%(34개 전부 불필요), 그래도 LayoutReader보다 절반 수준으로 덜 과다판정 |
| **권고** | 이 문서 유형(구조화된 정보박스+차트템플릿 중심 증권 리포트)엔 hard/easy 라우팅 자체가 불필요할 가능성 — MinerU 위임 이전에 "정말 이 문서군에 hard 라우팅이 필요한가"부터 재검토 가치 있음 |
| LayoutReader 최종 판단 | divergence를 그대로 hard/easy 판별 신호로 쓰는 건 **비권장** — 다른 용도(예: 진짜 리딩오더 복원기 자체)는 여전히 검토 가치 있으나 별도 검증 필요 |

---

## [35] 구조화 출력·청킹 병렬화 + 청크 텍스트 정규화 버그 수정 + BM25/BGE-m3-ko 인덱싱 틀

사용자 요청 3가지: (1) 구조화 출력을 청킹과 진짜 병렬로("스트럭처 아웃풋은 청킹과 병렬로 진행"),
(2) 텍스트가 잘 뽑히는지 확인, (3) BM25+BGE-m3-ko 하이브리드 인덱싱 틀 마련.

### (1) 진짜 파이프라이닝으로 교체

`[29]`는 "전체 문서 청킹을 다 끝낸 뒤 구조화 출력 API를 한꺼번에 병렬 디스패치"하는 방식이었음
(청킹 자체가 빨라서 손해는 작았지만 진짜 파이프라이닝은 아니었음). `process_pdf()`를 페이지
청킹이 끝나는 즉시 그 페이지의 구조화 출력 호출을 스레드풀에 바로 제출하도록 수정 —
다음 페이지 청킹(CPU)이 진행되는 동안 이전 페이지들의 API 호출(I/O)이 실제로 겹치게 함.
LGCNS(17청크 전부 structured_metadata 채워짐, 정확성 검증) 재확인 완료.

### (2) 텍스트 추출 품질 확인 중 발견한 버그 — 청크가 정규화를 안 거치고 있었음

인덱싱 틀을 테스트하려고 실제 하이브리드 검색을 돌려보다가(아래 (3)) Construct 청크의 raw_chunk에
PUA 문자(`U+F09F`, 장식용 불릿)가 그대로 남아있는 걸 발견. 원인: `extract_page_text()`(whole_page
baseline, recall 측정에만 쓰임)에는 PUA 제거+구두점/기호 정규화가 적용되는데, **실제로 임베딩·
검색 대상이 되는 청크 텍스트(`hierarchical_chunker._get_boxes_with_text()`, `get_textbox()` 원문)는
이 정규화를 전혀 거치지 않고 있었다** — [1]~[4]에서 검증한 정규화가 정작 검색 코퍼스에는
적용 안 되고 있었다는 뜻. `_clean_chunk_text()`를 추가해 `extract_page_text()`와 동일한 정규화
(PUA 제거+구두점/기호 정규화)를 청크 텍스트에도 적용하도록 수정. Construct 20개 청크 전부 PUA
0개로 확인, LGCNS/Construct recall 100%/100% 그대로(회귀 없음).

**부수 발견**: 이 수정으로 `hierarchical_chunker.py`가 `text_normalization`을 top-level import
하게 되면서, text_processing과 table_processing을 한 프로세스에서 같이 쓰는 평가 스크립트
(`compare_baseline_vs_pipeline.py` 등, 이름이 같은 두 `text_normalization.py`를 `sys.modules`
스왑으로 우회하던 스크립트들)에서 import 시점 문제로 ImportError 발생 — `hierarchical_chunker`를
스왑 전에 미리 import하도록 3개 스크립트 수정해 해결.

### (3) BM25 + BGE-m3-ko 하이브리드 인덱싱 틀

`pdf_pipeline/text_processing/index_text.py` 신규 — `build_index()`(청크 전체를 모아 BGE-m3-ko
임베딩 + BM25 인덱스 구축) / `hybrid_search()`(dense·BM25 점수를 min-max 정규화 후 가중합,
dense_weight=0.7/bm25_weight=0.3 기본값 — 다이어그램의 "핵심모델 DENSE, 보조모델 BM25"에 맞춤).
Supabase 스키마가 아직 확정 전이라 저장소는 인메모리(+ pickle 저장/로드 스텁)로 틀만 잡음 —
나중에 Supabase pgvector로 교체할 때 이 두 함수 내부만 바꾸면 호출부는 그대로.

**검증**: LGCNS/Construct 각각 인덱스 구축 후 실제 쿼리로 테스트. 텍스트로 답할 수 있는 질문
(예: "2분기 실적 컨센서스 대비 어떻게 예상되나", "이번주 건설업 수익률은 코스피 대비 어땠나")은
Construct 3/3, LGCNS 1/3이 top-1 정확 적중, 나머지도 top-3 안에는 들어옴. **다만 "목표주가"/
"주요주주" 같은 질문은 검색이 안 됨** — 확인해보니 이 정보가 애초에 텍스트가 아니라 표(Stock
Data 박스)에 있어서 텍스트 전용 인덱스로는 원천적으로 못 찾는 정보였음(표 파이프라인 소관) —
버그가 아니라 스코프 한계. 이건 다이어그램의 "엔티티 합성"(표+텍스트+이미지 결합) 단계가
왜 필요한지를 실측으로 재확인해준 셈 — 나중에 검색 품질 평가 골든셋을 만들 때 "텍스트로 답
가능한 질문"과 "표/이미지가 있어야 답 가능한 질문"을 구분해서 태깅해야 함.

**한계(기록)**: BM25 토크나이저가 형태소 분석 없이 단순 어절 분리라 짧은 청크에서 점수가
튀는 경우 관찰됨(LGCNS "K-IFRS 회계기준 개정" 문구가 무관한 질의에도 최고점 나온 사례) — 정교한
한국어 토크나이저 적용은 다음 개선 과제로 남김(지금은 틀 잡는 단계라 오버엔지니어링 방지).
numpy matmul에서 "divide by zero/invalid value" RuntimeWarning이 뜨는데, 임베딩 자체는
norm=1.0/NaN,Inf 없음을 직접 검증(Apple Silicon Accelerate BLAS의 알려진 무해한 경고로 판단,
`sector_classifier` 조사 때와 동일 결론).

### (4) 실측 — "PDF 하나 주면 얼마나 걸리나" (end-to-end: 분류+추출+청킹+BM25+임베딩 인덱싱)

| 구간 | 시간 |
|---|---|
| 모델 로드(YOLO+BGE-m3-ko, 서버 시작 시 1회성) | 4.36s |
| LGCNS(6p) 분류+추출+청킹+인덱싱(모델 로드된 상태) | 2.17s(분류 0.43s+추출/청킹 1.15s+BM25/임베딩 0.59s) |
| Construct(10p) 동일 | 2.41s |
| K-Wave(73p) 동일(추출/청킹이 지배적, `[32]` 참고) | 추정 ~11s(분류 ~5s+추출/청킹 ~5.3s+인덱싱 <1s) |

모델 로드는 서버 프로세스 시작 시 딱 한 번만 발생 — 그 이후 요청부터는 "웜" 수치가 실제 체감
지연. 6~10페이지짜리 개별 리포트는 실시간(2~3초)으로 처리 가능, 73페이지급 대형 문서는
`[32]`에서 이미 다룬 대로 추출/청킹 단계가 지배적 비용(스트리밍 제너레이터로 첫 페이지는
훨씬 빨리 나옴).

### [35] 종합 판정

| 항목 | 결과 |
|---|---|
| 청킹+구조화출력 병렬화 | 완료 — 페이지별로 청킹 끝나는 즉시 API 호출 제출, 진짜 겹침 |
| 청크 텍스트 정규화 버그 | 발견·수정 — 검색 코퍼스가 PUA/구두점 정규화 없이 임베딩되고 있었음, 회귀 없이 수정 |
| BM25+BGE-m3-ko 인덱싱 틀 | `index_text.py` 신규, 실제 쿼리로 검증 |
| 검색 품질 | 텍스트-답변 가능 질문은 대체로 양호(Construct 3/3 top-1) |
| 발견한 스코프 한계 | 표 전용 정보(목표주가/주요주주 등)는 텍스트 인덱스로 못 찾음 — 버그 아님, 엔티티 합성 단계 필요성 재확인 |

---

## [36] 정규화가 일반화 안 된 문제 — 전체 파이프라인 감사, 공유 모듈로 이전

`[35]`에서 발견한 "청크 텍스트가 정규화를 안 거친다" 버그가 일회성인지 사용자가 재차 확인
("이거 예전에도 문제 있었는데 정규화가 일반화가 안 돼?") — `pdf_pipeline` 전체에서 PDF 원문을
뽑는 모든 지점(`get_text`/`get_textbox`/pdfplumber `extract_text`/`extract_words`)을 grep으로
전수 조사한 결과, **PUA/구두점 정규화가 text_processing 안에서만 정의되고 사용되고 있었고
table_processing/sector_classifier 쪽의 다른 추출 지점들은 전혀 모르는 채로 작성됐음**을 확인:

| 지점 | 정규화 이전 상태 |
|---|---|
| `hierarchical_chunker.py`(청크 텍스트) | 없음 → `[35]`에서 수정 |
| `adaptive_table_router.py`의 `raw_text`(표 분류 + 구조화 출력 LLM 입력) | 없음 |
| `row_parser.py`의 셀 텍스트(TATR 그리드 + word-clustering 양쪽) | 없음(Hangul 과잉 띄어쓰기 정제만 있었음, 별개 관심사) |
| `sector_classifier.py`의 첫 페이지 텍스트(임베딩 대상) | 없음 |

**근본 원인**: 정규화 함수(`detect_pua_artifact`/`strip_pua_artifacts`/`normalize_punctuation`/
`normalize_symbols_and_whitespace`)가 `text_processing/text_normalization.py`에 갇혀있어서,
table_processing/sector_classifier를 작성할 때(각각 다른 시점, 다른 관심사로 작성됨) 이 함수의
존재 자체를 몰랐을 가능성이 높음 — "일반화가 안 된" 이유는 코드 위치 문제였음.

**수정**: PUA/구두점/기호 정규화 4개 함수 + 편의 함수 `clean_extracted_text()`를 `pdf_pipeline/
text_cleanup.py`(embedding.py/yolo_layout.py와 같은 공유 위치)로 이전. `text_processing/
text_normalization.py`는 삭제(내용이 전부 이동, 남은 게 없었음). 4개 지점 전부 
`clean_extracted_text()` 적용:
- `hierarchical_chunker.py` — 청크 텍스트(`[35]`에서 이미 적용, 이번에 공유 모듈로 재배선)
- `adaptive_table_router.py` — `raw_text`(표 분류 키워드 매칭 + `extract_table_metadata()` LLM 입력)
- `row_parser.py` — TATR 그리드 셀 텍스트 + word-clustering 라벨/값 텍스트(둘 다)
- `sector_classifier.py` — 섹터 분류용 첫 페이지 텍스트(임베딩 직전)

**부수 효과**: `text_processing`/`table_processing`에 이름이 같은 `text_normalization.py`가
둘 다 있어서 두 모듈을 한 프로세스에서 같이 쓰는 평가 스크립트들이 `sys.modules` 스왑으로
우회해야 했던 문제([26]~[35]에서 여러 번 등장)도 자연스럽게 해소 — 이제 이름 충돌 자체가 없어서
4개 스크립트(`compare_baseline_vs_pipeline.py`, `measure_structured_output.py`,
`analyze_kwave.py`, `evaluate_reading_order.py`)의 스왑 우회 코드를 전부 제거하고 평범한 import로
단순화.

**검증**: LGCNS/Construct 전체 파이프라인 재검증(text recall 100%/100%, 표 227/215행·hit_rate
11.9%/4.2% 전부 동일 — 회귀 없음), `sector_classifier.classify_pdf_sector()`도 재검증(LGCNS→통신업
conf 0.43, Construct→건설업 conf 0.49 — 기존 `[24]`에서 확인된 LG CNS의 서비스업/통신업 경계
애매 케이스와 동일한 결과라 회귀 아님).

### [36] 종합 판정

| 항목 | 결과 |
|---|---|
| 원인 | 정규화 함수가 text_processing 로컬에 갇혀 있어 다른 모듈이 존재를 모르고 작성됨 |
| 수정 | `pdf_pipeline/text_cleanup.py`로 이전, 4개 추출 지점(청크/표raw_text/표셀/섹터분류) 전부 적용 |
| 부수 효과 | text_normalization.py 이름 충돌 해소 → 4개 평가 스크립트의 sys.modules 스왑 우회 코드 제거 |
| 회귀 | 없음(텍스트 recall, 표 hit_rate, 섹터 분류 결과 전부 기존과 동일) |

---

## [37] 스케일링 대응 4건 + LayoutReader/MinerU 정량 비교

사용자 요청("1234 전부 손 볼 수 없나? 레이아웃판별모델 쓰면 4번은 지연/정확도 얼마나 늘어?
MinerU 차이는?")에 대한 대응.

### 구조화 출력 재시도/백오프(#2) — 완료
`tenacity`로 429/5xx/연결오류/타임아웃만 지수 백오프 재시도(최대 5회), 스키마 위반 같은 4xx는
즉시 실패(재시도해도 똑같이 실패하므로). 대형 문서에서 API 호출이 수백 건 나갈 때 레이트리밋에
그대로 죽던 문제 대응.

### 섹터별 구조화 출력(사용자 추가 요청) — 완료, 버그 1건 발견·수정
스키마를 섹터마다 N개 따로 만들지 않고(오버엔지니어링 방지), 이미 있는 `sector_schema.yaml`의
섹터별 큐레이션 지표를 프롬프트 힌트로 주입하는 방식 채택. **1차 테스트에서 진짜 문제 발견**:
힌트를 "이런 지표 나오면 놓치지 마세요"로만 주니 LLM이 실제 원문에 없는 지표(ARPU 등)를
metric_mentions에 지어냄(할루시네이션 유발). "참고용일 뿐, 원문에 실제로 없으면 지어내지
말라"는 경고 문구를 프롬프트에 추가해 재검증 — 수정 후 빈 chunk(관련 지표 없음)에서 정상적으로
빈 배열 반환 확인.

### TATR을 MPS로(#3) — 완료, 단 처음 측정치가 틀렸음을 재검증 중 발견
더미 이미지(800x500)로 처음 쟀을 땐 MPS가 2.79배 빠르다고 나왔는데, **실제 LGCNS 표 12개(300dpi
진짜 크롭)로 다시 재보니 322ms/표 -> 292ms/표로 겨우 9% 개선** — 작은 더미 이미지 벤치마크가
실제 워크로드를 대표하지 못했던 것. 배치 처리도 시도했으나 표마다 크기가 달라 가장 큰 쪽에
패딩하는 오버헤드가 배치 이득을 상쇄해 CPU에서 오히려 손해(기각). 9%는 크지 않지만 손해는
없어 그대로 적용. **교훈**: 이번에도 실제 데이터로 재검증 안 했으면 틀린 수치를 그대로 보고할
뻔함 — 합성 벤치마크는 항상 실제 워크로드로 재확인 필요.

### 페이지 단위 멀티프로세싱(#1) — 검토 후 보류(구현 안 함)
`[32]`의 프로파일링 기준 K-Wave 6.6초 중 병렬화 가능한 구간(get_textbox 등)은 최대 3초 정도.
워커마다 YOLO 모델을 새로 로드해야 하는 비용(워커당 ~1초, 병렬로 로드되니 워커 수와 무관하게
대략 1초 고정비)과 정확성 검증 부담(페이지 순서 보존, 프로세스 간 결과 병합) 대비 이득이
현재 문서 규모(최대 73페이지)에서는 크지 않다고 판단해 보류 — 문서가 수백 페이지급으로
커지면 재검토 가치 있음(설계는 이미 `[32]`에 스케치해둠).

### hard/easy 판정 신뢰도(#4) — LayoutReader 정량 비교

| | 지연 | 이 문서(K-Wave)에서의 "정확도" |
|---|---|---|
| 현재 룰베이스 | 페이지당 ~0ms 추가(이미 계산하는 신호 재사용) | Precision 0%(34개 hard 전부 클로드 판정상 불필요), Accuracy 53.4% |
| **LayoutReader 추가 시** | **+64ms/페이지**(실측) | Precision 0%(69개 전부 불필요 판정), **Accuracy는 오히려 5.5%로 더 나쁨** |

**정리**: LayoutReader를 hard/easy 판별 신호로 그대로 쓰면 지연은 페이지당 64ms 추가되는데
정확도는 오히려 룰베이스보다 나빠짐(`[34]` 참고) — "지연 늘리고 정확도도 떨어뜨리는" 최악의
조합이라 **이 용도로는 채택 안 함**. 다만 LayoutReader 자체의 정확도(예측 순서 자체의
BLEU/정렬 정확도)는 별도이고, "hard/easy를 나누는 판별기"로 쓰는 것과 "모든 페이지에 리딩오더
복원을 실제로 적용하는 것"은 다른 질문 — 후자는 이번에 검증 안 함(비용 대비 가치가 불확실해서
보류, `[34]`의 "다음 단계" 참고).

### MinerU와의 차이 — 로컬 미설치, 공식 벤치마크 기준 비교(주의: 실측 아님)

이번 세션에서 실제로 설치/실행은 안 함(설치 용량이 크고 의존성 충돌 위험이 있어 사용자 확인
없이 진행 안 하는 게 안전하다고 판단) — 대신 공식 벤치마크(OmniDocBench)로 비교:

| | 속도 | 정확도(공식 벤치마크 기준) |
|---|---|---|
| 우리 현재 파이프라인(easy 경로) | 페이지당 ~150~200ms(YOLO+PyMuPDF 추출+청킹) | LGCNS/Construct 텍스트 recall 100%(단, 좁은 태스크 — 단순 텍스트 추출만) |
| MinerU2.5-Pro-2605-1.2B(다이어그램에 명시된 버전) | **2.25 페이지/초(≈444ms/페이지)** | OmniDocBench 종합 90.67점, GPT-4o/Gemini-2.5-Pro/Qwen2.5-VL-72B보다 우수(레이아웃+표+수식 인식 포함) |

MinerU가 페이지당 **약 2~3배 느리지만**, 그 대신 레이아웃+OCR+표+수식 인식을 전부 한 번에
처리하는 훨씬 무거운 모델이라 단순 속도 비교는 공정하지 않음 — 우리 파이프라인의 "쉬운 페이지"
경로가 이미 처리 못하는 진짜 어려운 케이스(회전된 스캔본, 복잡한 다단 레이아웃)를 위한 도구라
그 지점에서 값어치가 나옴. **다만 `[34]`에서 K-Wave의 "hard" 34페이지 전부 실질적으로 리딩오더
문제가 없었다는 걸 감안하면, 지금 hard로 잘못 분류되는 페이지들을 MinerU로 보내는 건 불필요한
2~3배 지연을 감수하는 것 — hard/easy 판별 자체를 먼저 재검증하는 게 MinerU 도입보다 우선순위가
높다고 판단**(`[34]`의 결론과 일치).

Sources: [MinerU2.5 Hugging Face](https://huggingface.co/opendatalab/MinerU2.5-Pro-2605-1.2B),
[MinerU2.5 성능 리뷰](https://neurohive.io/en/state-of-the-art/mineru2-5-open-source-1-2b-model-for-pdf-parsing-outperforms-gemini-2-5-pro-on-benchmarks/)

### [37] 종합 판정

| 항목 | 상태 |
|---|---|
| #2 재시도/백오프 | 완료(tenacity, 429/5xx만 재시도) |
| 섹터별 구조화 출력 | 완료, 할루시네이션 버그 발견·수정 |
| #3 TATR MPS | 완료, 실측 재검증으로 최초 수치(2.79배)가 틀렸음을 발견 — 실제로는 9% |
| #1 멀티프로세싱 | 검토 후 보류(현재 규모에서 이득 대비 리스크가 안 맞음, 설계는 남겨둠) |
| #4 LayoutReader 정량 | 지연 +64ms/페이지, 정확도는 오히려 악화 — hard/easy 판별 용도로는 기각 |
| MinerU 비교 | 로컬 미실측(공식 벤치마크 기준), 2~3배 느림 — hard 판별 재검증이 먼저라고 판단 |

---

## [38] hard/easy 판별 로직을 클로드 판정에 맞춰 재구현

사용자 요청: "판별 자체 검증이 필요한 것 같아. 클로드 판정을 기준으로 거의 비슷하게 분류되도록
로직을 구현해줘." `[34]`의 클로드 전수 검토 GT(K-Wave 73페이지 중 리딩오더 복원 필요 0개)를
목표로 실제 분류 로직을 재구현.

**1차 시도 — material_overlaps에 인터리빙 조건 추가**: `[34]`에서 클로드가 확인한 핵심 통찰
— "컬럼이 겹친다"와 "실제로 헷갈린다"는 다르다. 컬럼이 여러 개라도 원문 추출 순서가 **컬럼별로
통째로 그룹화**돼 있으면(컬럼1 전체→컬럼2 전체→...) 문제없고, 순서가 컬럼 사이를 실제로
오가야(인터리빙) 진짜 문제. 새 함수 `_interleaving_excess()` 추가 — 원문 추출 순서를 그대로
따라가며 클러스터 전환 횟수를 세고, "이상적으로 그룹화됐을 때의 최소 전환 횟수"(클러스터 수-1)
대비 초과분을 계산(0=완전 그룹화, 클수록 인터리빙 심함). 검증(hand-crafted 유닛 테스트): 완전
그룹화 순서 → 0, 완전 인터리빙 순서 → 4, "제목 하나만 이탈" 순서 → 2(page3류 경계 사례에 해당).
`material_overlaps`가 있어도 `interleaving_excess >= 2`(임계치)를 동시에 만족해야 override
발동 — page3(실측 excess=1)는 정확히 걸러짐.

**1차 시도만으로는 불충분함을 재검증 중 발견**: 34개 hard 페이지 중 page3(material_overlaps
경로) 1개만 고쳐졌고 나머지 33개는 여전히 hard — 확인해보니 **가중합 점수(`score >=
hard_threshold`) 경로**로 별도로 hard 판정되고 있었음. 이 33개는 전부 rotation/font_variance/
figure_density가 밀어올린 점수였는데, `[34]`에서 이미 이 33페이지 전부를 클로드가 "리딩오더
문제 없음"으로 판정했었으므로, 이 신호들이 이 문서 유형(차트/표 중심 리포트)에서는 "리딩오더
필요성"과 상관관계가 없다는 게 실측으로 재확인된 것.

**최종 수정**: hard 판정을 가중합 점수 단독으로는 절대 못 내리게 변경 — `material_overlaps AND
interleaving_excess>=2`(둘 다 만족) 하나만 hard 판정 기준으로 남김. rotation/font_variance/
figure_density/가중합 점수는 `signals`에 참고용 진단 정보로만 남겨둠(나중에 진짜 hard 사례가
쌓이면 재캘리브레이션할 근거 자료로 보존, 지금 당장 hard 판정에 관여는 안 함).

**결과**:

| | 이전 로직 | 새 로직(클로드 GT 대비) |
|---|---|---|
| K-Wave hard 페이지 수 | 34개(전부 클로드 판정상 오탐) | **0개(클로드 판정과 정확히 일치)** |
| K-Wave 대비 정확도(TN/전체) | 53.4% | **100%**(TP=0, FP=0, FN=0, TN=73) |
| LGCNS/Construct hard 페이지 | 0개 | 0개(회귀 없음 재확인) |
| LGCNS/Construct recall | 100%/100% | 100%/100%(회귀 없음) |
| 표 처리 결과(간접 영향 확인용) | 227/215행, 27/9매칭 | 227/215행, 27/9매칭(동일) |

**한계**: (1) `min_interleaving_excess=2` 임계치는 K-Wave 1개 문서(진짜 양성 사례 0건 포함)로만
캘리브레이션됨 — 진짜 다컬럼 인터리빙 사례를 가진 PDF가 나오면 재검증 필요. (2) rotation/
font_variance/figure_density를 hard 판정에서 완전히 제외했는데, 회전된 스캔본처럼 컬럼 겹침
없이도 진짜 어려운 문서가 있다면 이 로직으로는 못 잡음 — 그런 실제 사례가 나타나면 그때
별도 신호로 재도입 검토.

**추가 검증(진짜 PDF positive 케이스 확보)**: 이전엔 hand-crafted 정수 시퀀스로만
`_interleaving_excess()` 수식을 검증했고, 실제 PDF 파일로 hard 경로가 발동하는지는
미확인 상태였음(3회 합성 PDF 생성 시도가 전부 PyMuPDF 블록 병합 문제로 실패). `insert_htmlbox()`를
컬럼 단위가 아니라 "왼쪽문단0→오른쪽문단0→왼쪽문단1→오른쪽문단1→..." 순서로 번갈아 호출해
컨텐츠 스트림 자체를 인터리빙시키는 방법으로 재시도 → 성공. 동일한 2단 레이아웃을
(a) 왼쪽 전체→오른쪽 전체 순서로 삽입(그룹화)한 버전과 (b) 문단 단위로 번갈아 삽입(인터리빙)한
버전 두 개를 만들어 `assess_page_difficulty()`에 실제로 통과시킨 결과:

| 합성 PDF | get_text 순서 | interleaving_excess | 판정 |
|---|---|---|---|
| 그룹화 버전 (`/tmp/synthetic_2col.pdf`) | L0..L5, R0..R5 | 0 | easy (정확) |
| 인터리빙 버전 (`/tmp/synthetic_interleaved2.pdf`) | L0,R0,L1,R1,... | 10 | **hard (정확)** |

이걸로 위 한계(1)의 "실제 PDF로 hard 경로가 발동하는 진짜 양성 사례가 없다"는 공백은 해소됨 —
알고리즘이 실제 PDF 파일 단위에서도 의도대로 동작함을 확인. 다만 이건 여전히 합성 데이터이고,
`min_interleaving_excess=2`라는 구체적 임계값 자체는 여전히 실제 증권사 리포트 유형의 진짜
양성 사례로 캘리브레이션된 적이 없다는 점은 그대로 남은 한계.

### [38] 종합 판정

| 항목 | 결과 |
|---|---|
| 목표 | 클로드 판정(K-Wave GT)과 룰베이스 hard/easy 분류를 최대한 일치시키기 |
| 핵심 통찰 | "컬럼이 겹친다" ≠ "헷갈린다" — 원문 순서가 컬럼별로 그룹화됐는지(인터리빙 여부)가 진짜 신호 |
| 수정 | `_interleaving_excess()` 신설 + material_overlaps override 조건화 + 가중합 점수 단독 hard 판정 제거 |
| 결과 | K-Wave 34개(전부 오탐) → 0개(GT와 완전 일치), LGCNS/Construct 회귀 없음 |
| 검증 방법 | 유닛 테스트(hand-crafted 그룹화/인터리빙 순서) + 전체 파이프라인 재검증(recall/hit_rate 불변) |

---

## [12] 전체 파이프라인 vs 베이스라인 비교(2개 PDF) — 텍스트 파트 결과

`page_classification -> text_processing.process_pdf() -> table_processing`을 실제로 연결해
LGCNS/Construct 2개 PDF에 돌린 결과. 텍스트 쪽 핵심 결과: **baseline(PyMuPDF raw) recall과
current(전체 정제+청킹) recall이 둘 다 100%** — 정제/청킹이 정보를 잃지 않으면서 구조 메타데이터를
추가한다는 뜻. (표 파트 결과 + 종합 결론 + 재현 방법은 `pdf_pipeline/실험_pipeline_baseline_비교.md`
전체 참고 — 두 모듈을 걸치는 비교라 별도 파일로 뺐음.)
