# 실험 기록 — 테이블 처리/고도화 (Table Processing)

## 범위
표의 **위치는 이미 안다고 가정**(`../page_classification/`에서 YOLOv11n으로 100% 정확도 확보 완료).
이 범주는 순수하게 "표 내용을 얼마나 잘 추출/구조화하고, 그걸로 엔티티를 얼마나 잘 뽑는가"만 다룬다.

## 대상 문서 / 정답
- `reference/20260721_company_279243000.pdf`(교보증권 LG CNS(064400) 기업분석, 6페이지, 표 14개)
- 엔티티 정답: `../ground_truth_064400.json`

## 참고사항
- 차후 VLM은 Qwen3-8B로 교체 예정(현재는 Qwen2.5-VL-7B 유지, 이미지 캡셔닝은 이 범주 밖)
- 평가 우선순위: **Recall > Precision**, 지연 감소하되 성능 저하가 크지 않으면 채택
- **PDF 1개(LG CNS 리포트) 샘플 실험** — 결론의 구체적 수치는 이 문서 특유의 레이아웃(특히 page4의 표 5~6개 밀집 구조)에 좌우된 부분이 많음. 다른 양식 PDF로는 재검증 필요.

---

## Docling과 TableFormer의 관계 (혼동 방지)

**경쟁 관계가 아니라 포함 관계다.**
- **Docling**: 레이아웃 감지 + 표 구조 인식 + OCR + 문서 조립을 오케스트레이션하는 문서 변환 프레임워크
- **TableFormer**: Docling 내부에서 "표의 행/열/셀 구조 인식"만 담당하는 IBM Research 모델(Docling의 한 부품)

지금까지 `DocumentConverter().convert()`로 부른 것은 Docling 전체 파이프라인이고, 실제 표 구조 인식은 그 안의 TableFormer가 수행한다. 그래서 "Docling vs TableFormer" 비교표는 만들 수 없다(엔진 대 자동차를 비교하는 격). 다만 최적화 여지는 있음: 우리는 YOLO로 이미 표 위치를 알고 크롭까지 했는데 Docling은 크롭 내부에서 레이아웃을 한 번 더 감지한다(중복). TableFormer를 더 저수준으로 직접 호출해 이 중복을 생략하면 속도 개선 가능성 있음 — **다음 최적화 후보로 기록만 해두고 미실행**.

---

## [0] 테이블 베이스라인 — pdfplumber (표 위치는 주어진 것으로 가정)

**이게 테이블 고도화의 출발점.** YOLOv11n이 찾은 표 bbox(픽셀좌표 → pt좌표 환산)에 pdfplumber `extract_table()`만 적용 — 표를 찾는 게 아니라 "찾은 표에서 내용을 얼마나 뽑아내는가"만 측정.

- 코드: `benchmark_table_baseline_pdfplumber.py`

| page | table | bbox 높이(px) | pdfplumber 행수 |
|---|---|---|---|
| 1 | 1 | 277 | 12 |
| 1 | 2 | 363 | 0 |
| 1 | 3 | 85 | 0 |
| 2 | 1 | 530 | 8 |
| 3 | 1 | 399 | 0 |
| 3 | 2 | 313 | 0 |
| 4 | 1 | 653 | 1 |
| 4 | 2 | 580 | 1 |
| 4 | 3 | 673 | 1 |
| 4 | 4 | 264 | 1 |
| 4 | 5 | 584 | 1 |
| 4 | 6 | 1260 | 1 |
| 5 | 1 | 340 | 2 |
| 6 | 1 | 40 | 2 |

- **총 14개 표, pdfplumber 총 30행 추출, 0행 표 4개**
- 특히 page4(재무제표 핵심 6개 표)는 전부 1행씩만 — 표 격자선은 있지만 셀 병합/여러 행 구조를 pdfplumber 라인 기반 전략이 못 살림
- page3(계약공시 표 2개)는 완전히 0행 — 테두리선 약함

**→ [1] Docling/TableFormer(240행, 아래)과 비교하면 8배 차이. 이게 고도화로 해결해야 할 핵심 문제.**

---

## [1] Docling(TableFormer) — YOLO 크롭별 개별 파싱

- 코드: `benchmark_docling_on_crops.py`

| 지표 | 값 |
|---|---|
| 총 처리 크롭 수 | 14 |
| **총 추출 행 수** | **240행** (baseline 30행 대비 **+700%**) |
| 첫 변환(모델 로딩 포함) | 7.2초 |
| steady-state 평균 | 약 1.5초/크롭 |
| 총 소요(순차) | 27.6초 |

- page4 표 하나(포괄손익계산서)에서만 pdfplumber 1행 → Docling **28행 전부 복원**
- 크롭 2개(page1_table_23, page6_table_4)는 Docling도 0행 — YOLO bbox가 실제 표가 아니었거나 크롭 부정확 추정

## [2] Docling 배치 처리 — 채택 안 함

같은 페이지 크롭들을 세로로 합쳐 페이지당 1회 호출로 축소.

| 지표 | 크롭별 개별(기존) | 페이지당 배치 |
|---|---|---|
| 호출 횟수 | 14 | 6 |
| 총 소요 | 27.6초 | 18.9초(-31.6%) |
| 총 행수 | 240 | **156(-35%)** |

**판정**: 지연은 줄지만 표 경계 혼동으로 품질 손실이 더 큼(-35% > -31.6%) → **기각**

## [3] Docling 프로세스 병렬 — 채택

Docling 표 구조 추론은 CPU 바운드(MPS 미사용)라 프로세스 병렬화로 지연만 줄이는 걸 시도.

| 시도 | 지연 | 비고 |
|---|---|---|
| 워커 6개, 태스크마다 모델 재로딩 | 29.1초(오히려 +5.3%) | 재로딩 비용이 병렬 이득 상쇄 |
| 워커 10개, 태스크마다 모델 재로딩 | 30.8초(오히려 +11.7%) | 워커 늘릴수록 로딩 경합만 커짐 |
| **워커 수 동적 산정 + 워커당 모델 1회 로딩(웜풀) + 스레드 오버섭스크립션 방지** | **10.65초(-61.4%), 240행 그대로** | **채택** |

- 코드: `benchmark_docling_parallel.py`
- 동적 워커 공식: `workers = min(len(table_crops), os.cpu_count(), MAX_WORKERS=8)` — PDF마다 표 개수가 다르므로 고정하지 않음(실측: min(14,14,8)=8 → 10.6초, min(14,14,8)=6도 10.65초로 유사, 병목이 가장 느린 크롭 1개(8초대)에 걸려있어 워커 6~8 사이는 차이 미미)

## [4] 표 크기 기반 라우팅(작은 표→pdfplumber, 큰 표만 Docling) — 채택 안 함

| 지표 | 값 |
|---|---|
| 작은 표(9개, <550px) pdfplumber | 25행 |
| 큰 표(5개) Docling 병렬 | 167행 |
| 합계 | 192행(전부 Docling 240행 대비 **-20%**) |
| 총 소요 | 9.42초(전부 Docling 병렬 10.65초 대비 **-11.5%**) |

**판정**: 품질 손실(-20%)이 지연 절감(-11.5%)보다 커서 **기각**. 병목은 큰 표 소수(특히 page4)라 작은 표를 스킵해도 병렬 처리 시 크게 안 빨라짐.

## [5] Docling 단독(1-Stage, YOLO 크롭 없이 PDF 페이지 직접 입력) — 비교

- 코드: `benchmark_docling_standalone.py`

| page | 소요(s) | 표(행수) | Picture | 분류 일치 |
|---|---|---|---|---|
| 1 | 9.1 | 3(29) | 3 | ✅ |
| 2 | 1.9 | 1(14) | 3 | ✅ |
| 3 | 1.3 | 2(9) | 3 | ✅ |
| 4 | 5.3 | 5(108) | 1 | ❌(image 오탐) |
| 5 | 0.7 | 1(3) | 2 | ✅ |
| 6 | 0.5 | 1(2) | 2 | ❌(image 오탐) |

총 18.9초(평균 3.14초/page), 165행. **판정**: 정확도는 준수하나 page당 3초는 느림 — 보류.

## [6] Unstructured(Hi-Res) — 탈락(설치 난관 + 극심한 느림)

- poppler·tesseract 필요 → Homebrew 없이 우회(PyMuPDF 렌더링 + PaddleOCR로 대체) 성공했으나
- 페이지 분류 정확도는 6/6(최고)이지만 **평균 23.7초/page**(page4는 69초) — 압도적으로 느림
- **판정**: 탈락. 배포 난이도도 높고(네이티브 의존성 2개), 속도도 최악.

## [7] YOLOv11n vs YOLOv26n — 표 구조화 품질 비교

(페이지 분류 자체는 `../page_classification/실험.md` 참고 — 둘 다 100%)

| 항목 | YOLOv11n | YOLOv26n |
|---|---:|---:|
| Table 크롭 수 | 14 | 13 |
| Docling Rows | **240** | 149(-38%) |
| 0-row Crop 개수 | 2 | 3 |

**판정**: YOLOv26n은 page4의 표를 더 잘게/부정확하게 쪼개 내용을 덜 복원 → **표 구조화는 YOLOv11n 유지**.

## [12] 크롭 고도화(Adaptive Padding + Caption 공간매핑 + DPI 부분 재렌더링)가 [7]의 격차를 좁히는가 — 채택 안 함

[7]에서 확인된 YOLOv11n(240행) vs YOLOv26n(149행) 격차를, 크롭 품질을 높이면 줄일 수 있는지 검증.

- 기법(크롭 생성 자체는 `../page_classification/실험.md` [3] 참고, YOLOv11n/YOLOv26n 공통 적용):
  1. Adaptive Padding: 상단 +35px(캡션 포함) / 좌우·하단 +12px(타이트, 인접 표 침범 방지)
  2. Spatial Nearest Caption Mapping: 표-캡션 최근접 거리 매칭(200px 초과 시 매칭 포기)
  3. DPI Sub-rendering: YOLO 탐지 150dpi 유지, 최종 크롭만 PyMuPDF `clip`으로 300dpi 부분 재렌더링
- 코드: `benchmark_docling_enhanced_crops.py` (Docling 프로세스 병렬 적용은 [3]과 동일 패턴 재사용)

| 모델 | 일반 크롭 | 고도화 크롭(패딩+캡션+DPI300 결합) | 행수 변화 | 지연 변화 |
|---|---|---|---|---|
| YOLOv11n | 240행, 10.65초 | **225행(-6.2%)**, **25.56초(+140%)** | 악화 | 대폭 악화 |
| YOLOv26n | 149행, 5.638초 | **164행(+10.1%)**, 6.218초(+10.3%) | 소폭 개선 | 소폭 악화 |

**판정**: **기각**(양쪽 모델 다 채택 기준 미달)

- YOLOv26n은 소폭 개선(149→164)했지만 YOLOv11n의 원래 성능(240행)에는 한참 못 미침 → **격차를 좁히긴 해도 닫지는 못함**
- YOLOv11n은 오히려 **품질도 나빠지고(240→225) 지연도 대폭 증가**(10.65→25.56초, 특히 page4의 표 하나가 300dpi 고해상도 렌더링으로 22.4초까지 치솟음)

### 대조군: 기본 패딩만 단독 적용(캡션매핑·DPI 변경 없이 150dpi 그대로 + 사방 12px 균일 패딩)

위 결합 실험만으로는 "패딩"과 "DPI 재렌더링" 중 무엇이 YOLOv11n을 악화시키고 무엇이 YOLOv26n을 개선시켰는지 분리가 안 됨 → 변수를 하나씩 격리해서 재측정(사용자 질문으로 추가 검증).

- 코드: `benchmark_docling_enhanced_crops.py` (`yolo11_padonly`/`yolo26_padonly` 타깃), 크롭 생성: `../page_classification/benchmark_padding_only_crop.py`

| 모델 | 일반 크롭 | **패딩만(150dpi 유지)** | 패딩+캡션+DPI300(결합) |
|---|---|---|---|
| YOLOv11n | 240행, 10.65초 | **220행(-8.3%), 10.536초(±0%)** | 225행(-6.2%), 25.56초(+140%) |
| YOLOv26n | 149행, 5.638초 | **148행(-0.7%, 사실상 불변), 5.463초(±0%)** | 164행(+10.1%), 6.218초(+10.3%) |

**분리된 결론**:
- **YOLOv11n의 품질 저하는 패딩 자체가 원인**(패딩만으로도 240→220행, -8.3%) — DPI 재렌더링을 더해도 220→225로 거의 안 바뀜(오차 수준). 이미 적절히 타이트한 bbox에 여백을 더하면 인접 표/여백이 섞여 TableFormer 구조 인식에 노이즈가 된다는 최초 가설이 맞았음. 반면 **지연 폭증(+140%)의 원인은 패딩이 아니라 DPI 300 업샘플링**(패딩만일 때는 지연 거의 그대로, 10.65→10.536초)
- **YOLOv26n의 소폭 개선은 패딩이 아니라 DPI 재렌더링이 원인**(패딩만으로는 149→148행, 사실상 무변화) — YOLOv26n은 bbox 자체가 더 작아서(타이트) 150dpi로는 픽셀 수가 부족한데, 300dpi로 재렌더링하면 같은 영역이 더 선명해져 TableFormer가 구조를 더 잘 인식. 즉 YOLOv26n에게 필요한 건 "여백"이 아니라 "해상도"였음
- **정리**: 두 모델에 필요한 게 정반대다 — YOLOv11n은 패딩이 해롭고(노이즈), YOLOv26n은 DPI가 이롭다(해상도 부족 보완). 하나의 결합 레시피로 둘 다 좋게 만들 수 없고, YOLOv26n의 DPI 이득(+10%)도 YOLOv11n의 절대 성능(240행)엔 못 미침 → **기존 채택(YOLOv11n 플레인 크롭) 유지**가 여전히 최선
- Caption 공간매핑 자체도 200px 임계값 적용 시 전체 표의 21~31%에만 실제 매칭(밀집 페이지는 표마다 전용 캡션이 없는 경우가 많음, 상세: `../page_classification/실험.md` [3]) → 표 전체를 아우르는 로컬 앵커로 쓰기엔 커버리지 부족. [11]의 문서 전체 앵커(자동 최빈값)를 대체하기보다 보조 정보 정도로만 가치가 있어, 별도의 엔티티 추출 재실험(v5)은 진행하지 않음.

---

## 엔티티 추출 통합 실험 (표 구조화 결과를 실제 파이프라인에 연결)

### [8] v2: 통짜 프롬프트(텍스트+표 전체+이미지설명 한 번에)

| 지표 | v1(pdfplumber 표) | v2(Docling 표로 교체) |
|---|---|---|
| Recall | 60.0%(6/10) | 60.0%(6/10) — **불변** |
| 총 처리시간 | 468.7초 | **1105.1초(+136%)** |

**원인**: page3 개선(+2 hit)과 page2의 degenerate 반복(-2 hit)이 상쇄. page4(표 5~6개 밀집)의 프롬프트가 거대해져 엔티티 추출 1회가 **566초** — 반복은 없었는데 순수 prefill(입력 처리) 비용.

**교훈**: 표 구조화 품질(행수) 개선이 엔티티 추출 성능/속도로 자동 연결되지 않는다.

### [9] v2+repetition_penalty=1.3

| 지표 | v2(penalty 없음) | **v2+penalty** |
|---|---|---|
| Recall | 60.0% | **90.0%(9/10)** |
| 총 처리시간 | 1105.1초 | 1097.5초 |

repetition_penalty 하나로 Recall +30%p. 단, **1.5 이상은 할루시네이션 유발**(실측: 1.5에서 "네이버클라우드"를 "삼성"으로 지어냄, 1.8은 완전 붕괴) → **1.3이 안전한 상한**. `no_repeat_ngram_size` 추가도 시도했으나 정확한 종목코드를 지어내는 부작용으로 기각.

남은 미스: 우리은행 1개(10개 중 9개 hit). page4는 여전히 614초(불변 — repetition_penalty는 생성 단계만 작용, page4는 입력이 긴 게 원인이라 효과 없음).

### [10] v3: 표 단위 분리(텍스트+이미지는 페이지 레벨, 표는 표마다 개별 호출)

| 지표 | v2+penalty | **v3(표 분리)** |
|---|---|---|
| Recall | 90.0% | **70.0%(-20%p)** |
| 총 처리시간 | 1097.5초 | **528.1초(-52%)** |

page4 페이지레벨 호출: 614초 → **11초**로 확인(반복 유발 구조적 차단, 목표 달성). 다만 표를 페이지 맥락 없이 고립시키니 page3(네이버클라우드/우리은행)를 놓치고, page4류 순수 숫자표에서 **"삼성전자", "TEZA" 같은 없는 회사를 할루시네이션**.

### [11] v4: v3 + 문서 앵커 자동 산출

- 앵커는 **고정 문자열이 아니라 페이지레벨 결과 전체에서 자동으로 최빈값을 산출**(하드코딩 없음 → 다른 PDF에도 자동 적용됨). 실측: 'LG CNS' 자동 도출
- 코드: `run_full_pipeline_v4_anchor.py`

| 지표 | v3(앵커 없음) | **v4(앵커)** |
|---|---|---|
| Recall | 70.0% | 70.0% — **불변** |
| 할루시네이션 | "삼성전자" 등 엉뚱한 회사 생성 | **해소**(틀린 회사 대신 "LG CNS(KOSDAQ: LGN)"처럼 세부정보만 부정확) |
| 총 처리시간 | 528.1초 | 521.9초 |

**판정**: 앵커는 할루시네이션(정밀도/신뢰성) 문제는 해결하지만 Recall(네이버클라우드·우리은행·국민연금공단 누락)은 못 고침 — 표 내용 자체를 더 명확히 구조화하거나, "계약상대방을 찾아라"류 표-타입-특화 프롬프트가 추가로 필요.

---

## [13] Adaptive Table Complexity Router — 표마다 단순/복잡 판정 후 라우팅

### 설계 배경

요청받은 파이프라인:
```
Table Page → YOLOv11n Table Detection → Table Crop → Table Complexity Router
  ├─ Simple Table → Fast Parser(pdfplumber, OCR+Rule)
  └─ Complex Table → Docling(TableFormer)
→ Structured Table JSON → Entity/Relation Extraction → KG+Vector Index
```

**[4](표 크기 기반 라우팅, 높이<550px)는 이미 기각된 전례가 있음**(품질 -20% > 지연 -11.5%). 원인은 "크기"와
"구조 복잡도"가 비례하지 않기 때문 — 실제로 page4의 표들은 다양한 높이(264px~1260px)를 가지지만
**전부** pdfplumber로는 1행만 뽑히는 최고 난이도 표들이다. 높이 264px짜리(page4_table4)는 [4]에서
"작은 표"로 분류되어 pdfplumber에 잘못 라우팅됐을 것 — 이게 [4]가 실패한 근본 원인.

그래서 이번엔 **크기 대신 "pdfplumber가 실제로 그 표를 읽어냈는가"를 직접 신호로 사용**(코드:
`adaptive_table_router.py`). 표마다 pdfplumber `extract_table()`을 먼저 공짜로 돌려보고(어차피 필요한 신호),
그 결과 자체의 품질로 복잡도를 판단:

| 신호 | 의미 |
|---|---|
| `quick_rows` | pdfplumber가 뽑은 행 수 |
| `expected_rows` | 표 bbox 높이(pt) ÷ **그 페이지의 실제 글줄 간격 중앙값**(pdfplumber `extract_words()`로 페이지마다 직접 계산 — 하드코딩 아님, PDF/DPI 달라져도 적응) |
| `fill_ratio` | quick_rows / expected_rows — "있어야 할 행의 몇 %를 뽑았나" |
| `consistent_columns` | 모든 행의 셀 개수가 같은가(다르면 병합 셀을 잘못 쪼갠 ragged 결과) |
| `nonempty_ratio` | 비어있지 않은 셀 비율(낮으면 병합 셀이 빈칸으로 잘못 분리됐다는 신호) |

**판정**: `quick_rows==0` 이거나 `quick_rows<2` 이거나 컬럼 비일관이거나 `nonempty_ratio<0.5`이거나
`fill_ratio<0.6`이면 COMPLEX(Docling) → 그 외엔 SIMPLE(pdfplumber 결과 확정, Docling 호출 자체를 생략).
전부 **절대 픽셀값이 아니라 비율/일관성 기반**이라 PDF마다 유동적으로 작동하도록 설계.

### Round 1: 초기 라우터(8워커, 순차 실행)

- 코드: `benchmark_adaptive_router.py v1`

| 페이지/표 | 판정 | 근거 |
|---|---|---|
| page1_table1 | **SIMPLE** | fill_ratio 0.79, 12행 |
| page1_table2, table3 | COMPLEX | quick_parse_empty(0행) |
| page2_table1 | COMPLEX | fill_ratio 0.15(있어야 할 54행 중 8행만) |
| page3_table1, table2 | COMPLEX | quick_parse_empty(0행) |
| page4_table1~6(전부) | COMPLEX | too_few_rows(전부 1행, fill_ratio 0.016~0.076) — **높이가 264px~1260px로 제각각이어도 전부 정확히 복잡으로 잡음(→ [4]의 실패 원인을 정확히 해결)** |
| page5_table1 | COMPLEX | sparse_cells(nonempty_ratio 0.43) |
| page6_table1 | **SIMPLE** | fill_ratio 1.19, 2행 |

| 지표 | [3] 전부 Docling 병렬(기존 채택) | [4] 크기라우팅(기각) | **[13] Round1** |
|---|---|---|---|
| SIMPLE/COMPLEX | 0 / 14 | 9 / 5(높이 기준, 오분류 포함) | **2 / 12(신호 기반, 정분류)** |
| 총 행수 | 240 | 192(-20%) | **242(+0.8%)** |
| Docling 단계 소요 | 10.65초 | 9.42초(-11.5%) | **10.927초(+2.6%, 오차범위)** |

**결과**: 품질은 [4]의 실패(-20%)를 완전히 피하고 오히려 소폭 개선(+0.8%)했지만, 지연은 거의 그대로.
원인: Docling으로 간 12개 표 중 page4의 6개가 여전히 병목(가장 느린 표 1개가 8.5초)이고, 라우터가 덜어낸
2개(page1_table1, page6_table1)는 원래도 빠른 표라 병목에 영향 없음 — **critical path가 안 바뀜**.

### Round 2(자가 피드백 1회차): 라우팅 판단과 Docling 풀 기동을 동시 진행 + 워커 10개로 상향 — 기각

가설: "YOLO+pdfplumber 라우팅 판단(2.2초)"과 "Docling 워커 풀 기동(프로세스 생성+모델 로딩)"은 서로
독립적이니 동시에 실행하면 더 오래 걸리는 쪽만큼만 대기하면 될 것 → 순차 실행 대신 겹쳐서 실행, 워커도
10개로 상향(남은 COMPLEX 표가 14→12개로 줄었으니 여유가 있다고 판단).

| 지표 | Round1(순차, 8워커) | **Round2(겹침, 10워커)** |
|---|---|---|
| 라우팅 판단 | 2.193초 | 3.23초(오히려 증가) |
| Docling 단계 | 10.927초 | 11.063초 |
| 총 소요 | 13.12초 | **14.293초(-9% 악화)** |
| page4_table6(최대 병목 표) | 8.563초 | 10.507초(+23%) |

**판정**: **기각**. 가설과 반대로 겹쳐 실행하니 메인 스레드(YOLO/pdfplumber)와 워커 프로세스들(Docling 모델
로딩)이 CPU를 놓고 서로 경합해 양쪽 다 느려짐. 개별 Docling 표 처리 시간도 워커를 10개로 늘리자 오히려
늘어남(8.5→10.5초) — 코어 경합이 순수 프로세스 수 증가만으로도 발생함을 확인.

### Round 3(자가 피드백 2회차): 겹침은 빼고 워커만 12개(COMPLEX 표 수와 정확히 일치, 단일 웨이브)로 — 기각

Round2의 악화가 "겹침" 때문인지 "워커 수 자체" 때문인지 분리하기 위해, 겹침 없이 워커만 12개로 상향(12개
COMPLEX 표를 웨이브 없이 한 번에 처리 시도).

| 지표 | Round1(8워커) | **Round3(12워커, 단일 웨이브)** |
|---|---|---|
| Docling 단계 | 10.927초 | **13.25초(+21% 악화)** |
| page4_table6 | 8.563초 | 11.865초(+39%) |

**판정**: **기각**. 웨이브를 없애도 오히려 더 느려짐 — 원인은 대기열(큐) 문제가 아니라 순수 **동시 실행
프로세스 수 자체가 늘면 코어/메모리 대역폭 경합으로 개별 Docling 추론이 느려지는 것**. [3]에서 이미 확인된
"워커를 늘릴수록 경합만 커진다"는 교훈이 모델 재로딩뿐 아니라 실제 추론 단계에도 그대로 적용됨을 재확인.
→ **기존 MAX_WORKERS=8이 여전히 최적**, 8을 넘기지 않는다.

### [13] 최종 판정

**채택 보류 조건부**: 라우터 자체(quality-safe 복잡도 판정 로직)는 [4]의 실패 원인(크기≠복잡도)을 정확히
해결하고 품질을 preserve(오히려 +0.8%)하지만, **이 PDF 샘플에서는 지연 개선 효과가 없음**(critical path가
page4의 대형/고밀도 표들에 고정되어 있고, 이들은 라우터도 정확히 COMPLEX로 판정해 Docling으로 보내기 때문).
표 14개 중 12개가 진짜로 Docling이 필요한 이 샘플에서는 라우터의 이득이 작지만, **SIMPLE 표 비중이 높은
문서(격자선이 뚜렷한 깔끔한 표 위주)에서는 같은 로직이 훨씬 더 많은 표를 Docling에서 덜어내 실질적인 지연
감소로 이어질 것으로 기대**(이 문서 특유의 재무제표 밀집 구조 때문에 이번엔 효과가 작게 나타남 — PDF
1건 기준 결론의 전형적 사례). Round1 설정(순차, 8워커)을 최종 라우터 구성으로 확정하고 실제 엔티티
추출 파이프라인에 연결해 Recall/Precision/F1까지 검증(아래).

### 전체 파이프라인 연동 (v5)

- 코드: `run_full_pipeline_v5_adaptive_router.py`, 결과: `result_pipeline_v5_adaptive_router_entities.json`,
  리포트: `실험_v5_adaptive_router_recall_report.md`

| 지표 | v2+penalty(전부 Docling, 기존 최선) | **v5(Adaptive Router)** |
|---|---|---|
| Recall | 90.0%(9/10) | **90.0%(9/10) — 동일**(미스도 동일하게 "우리은행" 1개) |
| Precision(근사) | 83.3% | **84.2%(근소 개선)** |
| F1(근사) | 86.5% | **87.0%(근소 개선)** |
| 표 단계 소요 | 11.422초(전부 Docling) | **12.437초**(라우팅 판단 1.736초 + Docling 10.701초, SIMPLE 2개/COMPLEX 12개) |
| 엔티티 추출 단계 | 695.524초 | 589.74초 |
| 총 처리시간 | 1097.51초 | **992.74초** |

**해석(과대평가 방지를 위해 정직하게 분리)**:
- **표 단계 자체는 라우터 도입으로 오히려 소폭 느려짐**(11.4→12.4초, +9%) — 라우터가 YOLO 탐지를 자체적으로
  다시 수행하기 때문(라우팅 신호 계산에 필요). page_classification 단계에서 이미 계산된 탐지 결과를 재사용하면
  이 오버헤드(약 1.7초)는 없앨 수 있으나, 이번엔 검증하지 않음(개선 여지로만 기록 — 전체의 0.2% 수준이라 재실행 비용 대비 이득이 작음)
- **총 처리시간 단축(1097.5→992.7초)의 실제 원인은 라우터가 아니라 엔티티 추출 단계 자체의 실행 간 편차**
  (695.5→589.7초) — page4 표 내용은 이번에도 전부 Docling으로 갔으므로(라우터가 page4의 6개 표를 전부
  올바르게 COMPLEX로 판정) v2와 사실상 동일한 입력이 들어갔다. 그런데도 소요시간이 달라진 건 Apple
  Silicon MPS 추론의 실행 시점별 편차(열 상태/메모리 압력 등)로 보는 게 타당 — **표 라우팅이 엔티티 추출
  속도를 직접 개선했다고 주장할 근거는 없음**
- **실제로 검증된, 라우터의 진짜 기여는 Recall을 잃지 않았다는 것**: SIMPLE로 분류돼 Docling을 건너뛴
  2개 표(page1_table1, page6_table1) 어디에도 목표 엔티티가 없었으므로 정보 손실 없이 안전하게
  넘어갔음이 확인됨 — [4](크기 기반 라우팅)가 만들었던 Recall 손실 위험을 이 설계는 재현하지 않았다

**최종 판정**: **품질 유지(무손실) 확인, 지연은 이 표본에서 유의미한 개선 없음** — 정보 손실 위험을
회피하면서도 성능 저하가 없다는 조건은 만족하므로 "안전한 대안"으로 채택 가능하나, 이 특정 PDF(재무제표
밀집형)에서는 실질적 속도 이득이 없어 [3](전부 Docling 병렬)을 대체할 강한 근거는 아직 없음. 표 구성이
더 단순한(깔끔한 격자 표 위주) 문서에서 재검증하면 라우터의 지연 이득이 더 뚜렷하게 나타날 것으로 예상.

---

## [14] Table-aware Entity Extraction 분기 — 진짜 병목은 표 추출이 아니라 엔티티 추출

### 문제 재정의

[13]까지의 모든 실험은 "표 추출(Docling)을 얼마나 빠르게 하느냐"에 집중했지만, 실측 수치를 보면:

| 단계 | 소요 | 비중 |
|---|---|---|
| 표 추출(Docling 병렬) | ~10~12초 | 총 시간의 1~1.2% |
| 엔티티 추출(LLM) | ~590~695초 | 총 시간의 **54~63%** |

**표 추출을 아무리 최적화해도 전체 지연의 1%대만 건드리는 것** — 진짜 병목은 엔티티 추출이고,
그 안에서도 page4(재무제표 6개 밀집)의 프롬프트 폭발(519~614초, 단일 페이지가 전체의 절반 이상)이
핵심 원인. 요청받은 구조:

```
Structured Table JSON → Table Type Classification
  ├─ Finance   → Rule Extractor(LLM 미사용)
  └─ Contract/General → LLM Extractor
```

### 설계

- **분류**: 표 텍스트에 재무제표/투자지표 키워드(매출액/영업이익/자산/부채/PER/PBR/EPS 등, 20개)가
  2개 이상 매칭되면 `finance`, 아니면 `contract_or_general`(코드: `table_type_router.py`)
- **재무제표(finance)**: LLM 호출 안 함. 대신 한국 기업/기관명 접미사 패턴(은행/증권/전자/화학/공단/
  클라우드 등 — 특정 회사명 하드코딩 아님, 일반화 가능) + 6자리 종목코드 정규식 + 자동 도출 문서 앵커로
  엔티티 후보를 규칙 기반으로만 스캔(비용 사실상 0)
- **문서 앵커 자동 도출**: "회사명 [종목코드]" 헤더 패턴(예: "LG CNS [064400]")을 페이지 텍스트에서
  정규식으로 스캔해 가장 빈번한 것을 앵커로 채택 — LLM 호출도 하드코딩도 없이 자동화(다른 한국
  증권사 리포트 헤더 포맷에도 일반적으로 적용 가능)
- **계약/일반(contract_or_general)**: 기존과 동일하게 표 마크다운을 LLM 프롬프트에 포함

### 구현 중 발견한 버그: Docling OCR이 한글 행 라벨을 깨뜨림

표 타입 분류를 처음엔 Docling 마크다운으로 시도했더니 page4의 재무제표 6개가 전부
`contract_or_general`로 잘못 분류됨. 원인 조사 결과 **Docling의 OCR이 밀집된 재무제표의 한글
행 라벨을 깨뜨리고 있었음**(예: "매출액"→"OH EOH", "영업이익"→"„0|9zz["로 파싱). 반면 같은 표
영역을 pdfplumber `extract_text()`로 읽으면 한글이 정확히 나옴(폰트/OCR 경로 차이로 추정 — 이
발견은 표 추출 품질을 "행 수"로만 측정해온 기존 실험([0]~[13])의 사각지대이기도 함: 행 수는
맞아도 라벨 텍스트 내용이 틀릴 수 있다는 뜻).
**수정**: 표 타입 분류는 항상 pdfplumber 원문 텍스트로 하고(Docling 마크다운은 다운스트림 LLM
콘텐츠 용도로만 사용) — `adaptive_table_router.py`에 `raw_text` 필드 추가.

### v6 1차 결과

- 코드: `run_full_pipeline_v6_table_aware.py`, 리포트: `실험_v6_table_aware_recall_report.md`

| 지표 | v2(전부 LLM) | v5(Adaptive Router) | **v6(Table-aware)** |
|---|---|---|---|
| Recall | 90.0%(9/10) | 90.0%(9/10) | **90.0%(9/10) — 동일** |
| 표 단계 | (표단계 포함 총합) | 12.4초 | 12.3초 |
| 엔티티추출 LLM 호출 | 6/6페이지 | 6/6페이지 | 6/6페이지(재무제표 8개 표는 규칙으로 우회) |
| 엔티티추출 단계 | 695.5초 | 589.7초 | **78.3초(-86.7%)** |
| 총 처리시간 | 1097.51초 | 992.74초 | **481.17초(-56.2%)** |

page4의 LLM 호출이 519~614초 → **10.7초**로 격감(가설대로 재무제표를 프롬프트에서 빼자 prefill
폭발이 사라짐). Recall도 동일 유지 — 사전 검증([13] 이후 본 실험 착수 전) 결과 타깃 엔티티 10개가
전부 (a) 페이지 본문/이미지설명(항상 LLM에 포함) 또는 (b) 계약형 표(page3, 여전히 LLM 라우팅)에만
존재하고 재무제표 표엔 없었기 때문 — 이 안전성 확인이 있었기에 손실 없이 채택 가능했음.

### 자가 피드백 Round 1: 근사 Precision 지표의 착시 발견 + Grounding Filter

**문제**: v6의 근사 Precision이 84.2%→**97.4%**로 급등 — 그러나 실제 출력을 들여다보니 page2에서
LLM이 "엘지네오티", "엘지씨알", "엘지데이터센타" 같은 **근거 없는 가짜 회사명을 21개나 연쇄 생성**함
(v5의 동일 page2 출력엔 이런 현상이 없었음 — page2의 표를 재무제표로 분류해 프롬프트에서 빼자,
모델이 "모든 기업 나열, 반복 금지"라는 지시 + `repetition_penalty=1.3`의 상호작용으로 실제 근거가
바닥나자 새 토큰을 지어내는 쪽으로 새어나간 것으로 추정). 기존 근사 Precision 지표는 작은
차단목록(`KNOWN_NON_ENTITIES` 3개)에 없으면 전부 정답으로 관대하게 처리해 이 할루시네이션을
전혀 못 잡아냈고, 오히려 겉보기 정밀도가 올라가는 **역설적 착시**를 만들었음.

**조치**: 각 페이지의 실제 소스(본문 텍스트+이미지설명)를 근거 코퍼스로 삼아, LLM이 주장한 후보가
그 코퍼스에 실제로 등장하는지 검증하는 **Grounding Filter** 추가(코드: `postprocess_grounding_filter.py`,
"엘지/LG" 접두사 동일시 등 최소한의 정규화만 적용, 특정 회사명 하드코딩 아님). 재실행 없이 후처리만으로
적용 가능(엔티티 추출 자체가 이미 78초로 저렴해져서 사실 재실행도 부담 없었지만, 후처리가 더 빠름).

**검증을 위해 v5/v2에도 동일 필터를 소급 적용**(공정 비교):

| 지표 | v2(grounded) | v5(grounded) | v6(필터 전, 착시) | **v6b(v6+Grounding Filter)** |
|---|---|---|---|---|
| Recall | 90.0% | 90.0% | 90.0% | **90.0%** |
| Precision | 81.2% | 82.4% | 97.4%(착시) | **94.4%** |
| F1 | 85.4% | 86.0% | 93.5%(착시) | **92.2%** |
| 제거된 후보 | 3개(업계/엑소/엣지, 경미) | 3개(동일) | - | **21개(엘지네오-X 계열 등, 심각)** |

Grounding Filter를 공정하게 전 버전에 적용하니 **v6b의 94.4% Precision은 착시가 아니라 진짜
개선**임을 확인(v5/v2의 grounded Precision은 81~82%대에 그침) — 이유는 v6b가 애초에 page4의
재무제표를 LLM에 안 보내 "기타특수관계자"/"대외고객" 같은 표-라벨发 노이즈 자체가 원천 차단됐기
때문(v2/v5는 이런 노이즈가 있었지만 하필 차단목록에 걸려 fp로 잡혔던 것). 다만 이 필터는 "지표
보정용 트릭"이 아니라 **실제 프로덕션에서도 필요한 안전장치**로 채택해야 함 — 할루시네이션된
가짜 엔티티가 그대로 KG/벡터 인덱스에 들어가면 실사용 단계에서 문제가 되기 때문.

### 자가 피드백 Round 2: max_new_tokens 축소로 할루시네이션 원천 차단 시도

가설: page2가 200토큰을 다 채우려고 근거 없는 내용을 지어내는 것이라면, 생성 길이 자체를 줄이면
할루시네이션이 원천적으로 줄어들 것 — `max_new_tokens=200→150`으로 재실행(코드:
`run_full_pipeline_v6c_shorter_gen.py`, 표단계는 [13] round1 설정 그대로 재사용이라 재검증 불필요).

| 지표 | v6(200토큰) | **v6c(150토큰)** |
|---|---|---|
| Recall | 90.0% | **90.0% — page3 등 정상적으로 긴 리스트도 안 잘림, 안전 확인** |
| 엔티티추출 단계 | 78.3초 | **60.1초(추가 -23.3%)** |
| 총 처리시간 | 481.17초 | **462.8초(추가 -3.8%)** |
| Grounding Filter 적용 후 제거된 가짜 후보 | 21개 | 16개(줄었지만 **여전히 발생**) |
| Grounding Filter 적용 후 최종 Precision/F1 | 94.4% / 92.2% | **94.4% / 92.2% — 동일** |

**판정**: 생성 길이를 줄이면 지연은 추가로 줄고(150토큰이 200토큰보다 빠르니 당연) 할루시네이션
"양"은 줄어들지만(21개→16개), **근본 원인은 해결 안 됨**(150토큰에서도 여전히 가짜 이름을 지어내다가
예산이 먼저 바닥나 멈추는 것뿐) — 즉 max_new_tokens 축소는 유용한 보조 최적화이지만 Grounding
Filter를 대체할 수 없다. **최종 채택: max_new_tokens=150 + Grounding Filter 둘 다 유지.**

### [14] 최종 채택 구성 및 종합 비교

| 지표 | v2(베이스라인) | v5(표 라우터만) | **v6c(Table-aware + 150토큰 + Grounding Filter, 최종)** |
|---|---|---|---|
| Recall | 90.0%(9/10) | 90.0%(9/10) | **90.0%(9/10) — 동일(미스: 우리은행, page3 표 인식 이슈로 표 타입 라우팅과 무관)** |
| Precision(grounded, 공정비교) | 81.2% | 82.4% | **94.4%** |
| F1(grounded) | 85.4% | 86.0% | **92.2%** |
| 총 처리시간 | 1097.51초 | 992.74초 | **462.8초** |
| **베이스라인 대비 지연 감소** | - | -9.5% | **-57.8%** |

**핵심 교훈**: 표 추출 최적화([1]~[13])는 전체 지연의 1%대만 좌우했지만, 엔티티 추출 단계 구조를
바꾼 [14] 하나로 전체 지연을 **57.8%** 줄이고 품질(Precision/F1)까지 개선했다 — "병목이 어디인지
직접 측정하고 그걸 고치는 것"이 부분 최적화보다 압도적으로 효과적이었다는, 이 프로젝트 전체를
관통하는 결론.

---

## [15] 표 라우팅(Docling) 단계 자체의 추가 latency 레버 탐색 — 둘 다 기각

[14] 이후 표 단계는 전체의 2.6%뿐이라 우선순위가 낮지만, 그동안 안 건드렸던 Docling 자체의
설정 2가지를 표 라우팅 단계 안에서만 격리 테스트(프로세스 병렬 변수 배제, COMPLEX 12개 크롭
순차 처리로 순수 설정 효과만 측정. 코드: `benchmark_docling_fast_mps.py`).

| 설정 | 순차 총 소요(12개) | 총 행수 | 판정 |
|---|---|---|---|
| CPU + TableFormerMode.**ACCURATE**(현재 기본값) | 20.24초 | 228행 | 기준 |
| CPU + TableFormerMode.**FAST** | **40.29초(오히려 +99%)** | 226행(동일) | **기각** — 이름과 반대로 이 워크로드에선 2배 더 느림 |
| **MPS**(Apple GPU) + ACCURATE | **28.02초(+38%)** | 228행(동일) | **기각** — 배치=1(크롭 1장씩)이라 GPU 전송 오버헤드가 이득보다 큼 |

**결론**: 이름이나 "GPU=빠름"이라는 통념과 반대로 둘 다 현재 설정(CPU+ACCURATE)보다 느렸다 —
직접 재보지 않았으면 "FAST 모드로 바꾸면 되겠지"라고 잘못 결론 내렸을 사례. 표 라우팅 단계는
현재의 CPU+ACCURATE+프로세스 병렬(8워커) 조합이 이 표본에서 이미 최적이며, 남은 이론적 레버는
[13]/[14] 정리에서 이미 적어둔 "TableFormer 직접 호출로 Docling 자체 레이아웃 재탐지 생략"(Docling
내부 구조 접근이 필요해 미검증) 정도만 남음 — 이마저도 표 단계가 전체의 2.6%뿐이라 실익은 작음.

---

## [16] Table Transformer(TATR, Microsoft, CVPR 2022) — 지금까지 없었던 TSR 모델 비교

사용자 지적: 지금까지 pdfplumber vs Docling(TableFormer) 비교뿐이었고, 논문에서 흔히 쓰는 별도
TSR(Table Structure Recognition) 모델과의 비교가 없었음. `microsoft/table-transformer-structure-recognition`
(HuggingFace 다운로드 가능, DETR 기반, row/column/spanning-cell bbox 탐지)을 실제로 받아 비교.

### 1차: 순수 구조 탐지 개수 비교(코드: `benchmark_tatr_comparison.py`)

| 모델 | 12개 COMPLEX 크롭 순차 처리 시간 | 총 detected rows |
|---|---|---|
| Docling(TableFormer) | 20.24초 | 228행 |
| **TATR** | **1.38초** | 242행(+spanning-cell 13개 별도 탐지) |

**주의**: TATR은 구조(bbox)만 뱉고 텍스트 추출은 안 함 — Docling의 20.24초엔 OCR+텍스트까지 포함이라
공정한 비교가 아님. 그래서 2차로 TATR이 찾은 row bbox를 pdfplumber로 실제 텍스트까지 채워
"최종 사용 가능한 표" 기준으로 재비교.

### 2차: TATR(구조) + pdfplumber(텍스트 채움) — 진짜 공정 비교(코드: `benchmark_tatr_full_pipeline.py`)

TATR이 찾은 각 row bbox(크롭 로컬 좌표) → 크롭의 페이지 내 오프셋 반영 → 150dpi px→pt 환산 →
pdfplumber `crop().extract_text()`로 실제 텍스트 채움. 텍스트가 실제로 있는 row만 "사용 가능한 행"으로 카운트.

**비교 기준 정정**: 위 1차/아래 표에서 쓴 "20.24초"는 [15]에서 TableFormerMode/AcceleratorDevice
효과만 순수하게 격리 측정하려고 일부러 순차 처리로 돌린 실험값이다 — 실제 1차 고도화에서 채택된
모델은 [3]의 **프로세스 병렬(8워커)** 버전이므로, 이 12개 COMPLEX 표를 8워커 병렬로 돌리면 몇 초인지
[13] Round1 결과([13] 참고)에서 재확인: **10.927초**(228행, 워커 8개). 아래 배속 계산은 이 기준으로 정정.

| 방식 | 12개 표 처리 시간 | 최종 사용 가능 행수 |
|---|---|---|
| Docling(TableFormer), 순차(참고용, [15]의 변수격리 실험값) | 20.24초 | 228행 |
| **Docling(TableFormer), 8워커 프로세스 병렬(1차 고도화 실제 채택 모델, [3]/[13])** | **10.927초** | 228행 |
| **TATR(구조) + pdfplumber(텍스트)** | **3.25초** | **228행 — 완전히 동일** |

**표 단위로 뜯어보면 더 흥미로움**(개별 표는 서로 다르게 이기고 짐, 우연히 합계만 같음):
- `page_1_table_3`: Docling 0행(OCR 실패) → **TATR+pdfplumber 7행 복원**(Docling이 완전히 놓친 표를 살림)
- `page_4_table_6`: Docling 60행 → TATR+pdfplumber 63행(비슷하거나 더 나음)
- `page_3_table_2`: Docling **11행(전부 OCR 쓰레기: "8209 8", "Al 92" 같은 무의미한 파편)** vs
  TATR+pdfplumber **0행(정직한 결과)** — 이 영역은 YOLO가 "Table"로 오탐한 차트([도표5] 매출&OPM
  추이)라 실제 텍스트가 없는데, Docling은 OCR을 강행해 그럴듯한 가짜 행을 만들어냄. TATR+pdfplumber는
  pdfplumber가 진짜 텍스트 유무를 확인하므로 이런 오탐에 더 강건함(가짜 데이터를 하위 LLM에 넘기지 않음)

**판정**: **동일 품질(228=228), 실제 채택 모델(프로세스 병렬 Docling, 10.927초) 대비 3.36배 빠름**
(순차 Docling 대비로 계산한 6.2배는 비교 기준이 잘못된 수치였음 — 정정), 게다가 OCR 오탐 상황에
더 정직함 — 이번 세션에서 나온 가장 강력한 미검증 대안. 다만:
- 표 단계는 이미 전체 파이프라인의 2.6%뿐이라([14] 이후) 총 지연 임팩트는 작음(약 7.7초 절감 여력 — 10.927→3.25초, 462.8초 중)
- TATR은 row bbox만 주므로 실제 채택하려면 pdfplumber 텍스트 매핑 로직을 프로덕션 코드로 옮겨야 함(이번엔 검증용 스크립트로만 구현)
- **PDF 1건 기준**이라 다른 문서에서도 이 우위가 재현되는지 추가 검증 필요(특히 pdfplumber가 임베디드
  텍스트 레이어 없는 스캔 PDF에선 무용지물 — 이 방식은 "텍스트 레이어가 있는 디지털 PDF"에서만 유효,
  스캔본은 Docling의 내장 OCR이 필요)

**결론**: 표 단계 자체의 latency는 이미 무시할 수준(2.6%)이라 당장 채택 우선순위는 낮지만, "텍스트
레이어가 있는 PDF + 표 위치를 이미 아는 상황"이라는 이 프로젝트의 조건에서는 **Docling 통째 대신
TATR(구조)+pdfplumber(텍스트) 조합이 이론적으로 더 우수한 대안**으로 기록. 표 단계가 병목인 다른
PDF/상황에서는 최우선 채택 후보.

### 나머지 제안 기법 검토 (실측 가능 여부 판단)

| 기법 | 판단 |
|---|---|
| Learned Complexity Router(MobileNet 등) | **이번엔 실측 불가** — 라벨링된 학습 데이터가 이 PDF 14개 표뿐이라 절대 부족(과적합 확실). 여러 PDF에 걸친 수백~수천 개 라벨링된 표 데이터가 있어야 의미 있는 실험이 됨. [13]의 rule-based 라우터(fill_ratio)가 이미 [4]의 실패 원인은 해결해서, 데이터 없이 당장 얻을 이득 대비 비용이 큼 |
| Adaptive/Dynamic Resolution | 이미 [12]에서 검증(YOLOv26n엔 DPI 300 재렌더링이 도움, YOLOv11n엔 역효과) — 사용자가 준 힌트(149→164행)와 정확히 일치하는 실험이 이미 있음 |
| Structure Recovery(Header/Span) | TATR이 `table column header`/`table spanning cell` 클래스를 이미 직접 출력함(위 실험에서 spanning cell 13개 탐지 확인) — TATR 채택 시 "덤"으로 따라오는 기능. Docling 단독으로는 별도 후처리 필요(미검증) |
| Confidence-based Parsing | [13]의 fill_ratio/컬럼일관성/빈셀비율 자체가 "confidence 기반 라우팅"의 rule-based 버전 — 이미 사실상 구현되어 있음 |
| Cell Graph Representation | 표 내용을 어떻게 "저장"할지의 문제라 recall/latency로 측정 가능한 실험이 아님 — 다음 단계(KG 적재) 설계 시 고려할 표현 방식 문제로 남겨둠 |
| HTML Output 유지 | Docling은 `export_to_html()` 지원(확인함) — rowspan/colspan 보존 가능. 다만 지금 엔티티 추출 프롬프트는 markdown으로 충분해 측정 가능한 성능 차이가 없어 미실행 |
| OCR Confidence 활용 | Docling이 문자 단위 OCR confidence를 노출하는지는 API 조사 필요(미확인) — TATR+pdfplumber 조합은애초에 OCR 자체를 안 쓰므로(임베디드 텍스트 직접 사용) 이 문제 자체가 회피됨 |
| Table Transformer(TATR) | ✅ **위에서 실측 완료** |
| Benchmark Dataset(PubTables-1M 등) | 이 프로젝트는 PDF 1건 실측 중심이라 공개 데이터셋 재현은 범위 밖 — Related Work 인용용으로는 유효하나 실험 항목은 아님 |

---

## [17] TATR × (No/일반/Adaptive Padding) × (150/200/300dpi) 3x3 그리드

[16]에서 검증한 "TATR(구조) + pdfplumber(텍스트 채움)" 조합에, [12]에서 만들었던 3가지 패딩
스타일(No padding, 균일 padding, Adaptive padding)과 3가지 렌더링 DPI(150/200/300)를 모두 교차
적용해 최적 조합을 탐색. 패딩은 물리적 크기(pt)로 고정해 DPI와 독립적으로 비교(코드:
`benchmark_tatr_padding_dpi_grid.py`).

| 조합 | usable rows(12개 표 합계) | 소요(초) |
|---|---:|---:|
| no_padding + 150dpi | 225 | 3.39 |
| no_padding + 200dpi | 227 | 2.00 |
| no_padding + 300dpi | 230 | 2.08 |
| padding + 150dpi | 239 | 2.05 |
| padding + 200dpi | 237 | 2.05 |
| padding + 300dpi | 234 | 2.13 |
| adaptive_padding + 150dpi | 240 | 2.04 |
| adaptive_padding + 200dpi | 239 | 2.08 |
| **adaptive_padding + 300dpi** | **242(최고)** | 2.11 |

(참고: Docling 베이스라인 228행 — 순차 20.24초 / **실제 채택 모델인 8워커 프로세스 병렬은 10.927초**,
[16]의 TATR-무패딩-150dpi 상당 228행/3.25초)

### 핵심 발견: TATR은 [12]의 Docling 결론과 정반대로 패딩에서 이득을 본다

- [12]에서 Docling/TableFormer는 **패딩을 추가하면 오히려 품질이 나빠짐**(YOLOv11n 240→225행,
  인접 표/여백이 섞여 노이즈가 된다고 결론)
- 반면 **TATR은 패딩이 있을수록, 그리고 adaptive(비대칭)일수록 꾸준히 더 좋음**
  (no_padding 225~230 < padding 234~239 < **adaptive_padding 239~242**, DPI 무관하게 이 순서가
  거의 항상 유지됨)
- **해석**: TATR(DETR 기반 object detection)은 표 전체의 "경계"를 명확히 봐야 첫/마지막 행을 놓치지
  않고 정확히 detect하는 구조라, 약간의 여백이 오히려 도움이 되는 것으로 보인다. Docling은 자체
  내부 레이아웃 재탐지 단계가 있어 여백에 섞인 인접 요소(다른 표, 캡션)를 노이즈로 오인하는 반면,
  TATR은 그런 재탐지 단계 없이 곧바로 구조를 예측해 이 부작용이 없는 것으로 추정
- DPI 자체의 효과는 패딩보다 작고 방향도 일관되지 않음(no_padding에선 DPI 올릴수록 소폭 개선,
  padding에선 오히려 소폭 감소) — **패딩 스타일이 DPI보다 더 지배적인 변수**

**결론**: **모델(TSR 아키텍처)마다 크롭 전처리(패딩)의 최적값이 다르다** — "패딩이 좋다/나쁘다"는
일반 결론이 아니라 Docling엔 해롭고 TATR엔 이롭다는 **모델-특이적** 결론. TATR을 채택한다면
`adaptive_padding + 300dpi`(242행, 2.11초 — Docling 8워커 병렬(10.927초) 대비 품질 +6.1%,
속도 **5.18배**[정정: 이전에 순차 Docling 20.24초 기준으로 잘못 계산했던 "9.6배"를 실제 채택
모델 기준으로 수정])가 이 표본에서
최적 조합. Docling을 계속 쓴다면 [12]의 결론대로 패딩 없이 원본 bbox 그대로가 최선.

### [17] 추가 검증: TATR을 "무조건 전부"에 써도 되는가 — 아니오, [13] 라우터는 여전히 필요

[13]에서 SIMPLE로 분류돼 pdfplumber 단독으로 처리 중인 2개 표에도 TATR+pdfplumber를 적용해봤더니
**오히려 후퇴**했다:

| 표 | pdfplumber 단독(기존, 채택) | TATR+pdfplumber |
|---|---:|---:|
| page1_table1(12행, 깔끔한 표) | 12행 | 11행(**-1**) |
| page6_table1(2행, 높이 40px 초소형 표) | 2행 | **0행(전부 유실)** |

TATR은 CONF_THRESHOLD=0.6 기준으로 row를 탐지하는데, 아주 작거나 이미 구조가 명확한 표에서는
탐지 자체가 실패하거나 일부를 놓친다(특히 초소형 표는 TATR 학습 데이터에서 희귀한 케이스로 추정).
즉 **TATR은 COMPLEX 표(pdfplumber가 실패하는 표)에서만 Docling보다 우수**하고, 이미 pdfplumber가
잘 처리하는 SIMPLE 표에는 오히려 손해다.

**최종 결론**: [13]의 SIMPLE/COMPLEX 라우팅 구조는 그대로 유지하고, **COMPLEX 표의 처리 엔진만
Docling → TATR(+adaptive_padding+300dpi)+pdfplumber로 교체**하는 것이 맞다. "표는 무조건 TATR
하나만 쓰자"는 성립하지 않는다 — 표 크기/복잡도에 따라 최선의 도구가 다르다는, 이 프로젝트 전체를
관통하는 결론([4]의 실패, [12]의 모델별 패딩 차이와 같은 계열의 교훈)이 세 번째로 재확인됐다.

**갱신된 최종 표 처리 파이프라인(제안, 표 단계 latency 관점에서 미반영 상태 — 다음 세션 채택 후보)**:

```
Table Crop
    │
    ▼
Adaptive Complexity Router([13], fill_ratio 등)
    │
    ├─ SIMPLE  → pdfplumber 단독(변경 없음)
    │
    └─ COMPLEX → TATR(adaptive_padding+300dpi) + pdfplumber 텍스트 매핑  ← Docling에서 교체
```

예상 효과(이 표본 기준, 미실측): 표 단계 소요가 기존 Docling 병렬 처리(~11~12초) → TATR 기반
(~2~3초)로 줄어 총 파이프라인의 2.6%였던 표 단계가 1% 미만으로 축소. **단, 표 단계는 이미 비중이
작아 총 지연 임팩트는 미미**(462.8초 중 최대 10초 안팎 절감) — 아래 참고.

## [18] "표는 무조건 TATR 고정"이 안전한지 최종 검증 — DPI 확장 + 실제 파이프라인 실측

### DPI 확장: 300dpi가 진짜 최적점인가

[17]에서 300dpi가 3개 후보(150/200/300) 중 최고였을 뿐이라 진짜 최적점인지 400/500/600dpi까지
확장 검증(adaptive_padding 고정, 코드: `benchmark_tatr_padding_dpi_grid.py extended`).

| DPI | usable rows |
|---|---:|
| 300 | 242 |
| 400 | 240 |
| 500 | 242 |
| 600 | 240 |

**300dpi 이후로는 완전히 평평함(±2행 오차범위, 개선 없음)** — 300dpi가 진짜 플래토(더 올려도 무의미).
동일 설정 재실행으로 결정성도 확인(242행 재현). **300dpi 고정은 검증된 최적 파라미터.**

### 실제 엔티티 추출 파이프라인 검증(v7) — TATR로 사상 첫 Recall 100% 달성

[13]의 SIMPLE/COMPLEX 라우팅은 유지하고 COMPLEX 표의 엔진만 Docling → TATR(adaptive_padding+300dpi)
+pdfplumber로 교체해 v6c와 동일한 전체 파이프라인(표 타입 분기 + Grounding Filter + max_new_tokens=150)에
연결(코드: `run_full_pipeline_v7_tatr_table.py`).

| 지표 | v6c(Docling, 최종 그라운딩 적용) | **v7(TATR, 최종 그라운딩 적용)** |
|---|---|---|
| Recall | 90.0%(9/10, "우리은행" 누락) | **100.0%(10/10) — 사상 첫 만점** |
| Precision(grounded) | 94.4% | **93.3%** |
| F1(grounded) | 92.2% | **96.6%** |
| 표 단계 | 12.16초(Docling) | **4.11초(TATR)** |
| 엔티티추출 단계 | 60.1초 | **98.6초(오히려 증가)** |
| 총 처리시간 | 462.8초 | **493.25초(+6.6%, 오히려 증가)** |

**왜 "우리은행"을 드디어 잡았나**: TATR이 page3 계약표를 row 단위로 쪼개 pdfplumber로 각 행을
독립적으로 읽어오니(`tatr_extract_table()`의 row-by-row 매핑), 기존에 문제였던 "글자간격 손상+
'외 1' 접미사가 한 덩어리로 뭉쳐 인식되던" 현상이 사라짐 — row 경계가 명확해지자 LLM이 "주식회사
우리은행 외 1"을 정확히 하나의 엔티티로 읽어냄. [4]/[13]/[14] 어떤 기법도 못 고쳤던 마지막 Recall
갭이 여기서 해소됨.

**하지만 총 지연은 늘었다 — 정직하게 원인 분석**: 표 단계는 8초 줄었는데(12.16→4.11초) 엔티티추출
단계가 38.5초 늘어(60.1→98.6초) 순손실 +30.5초. page3 LLM 호출이 13초→27.3초로 늘어난 게 주범 —
TATR의 row 단위 텍스트가 Docling 마크다운보다 정보가 풍부해지자(정확한 회사명까지 잡아내니) LLM이
"LG전자의 계약 당사자들(NH농협은행, 우리은행 외 1곳, 우리은행 외 2곳): ..." 식으로 더 장황하게
설명하며 답변을 생성 — **출력 품질이 좋아진 대가로 출력 길이(=생성 시간)가 늘어난 것**. 표 처리
자체의 문제가 아니라 표 처리 개선이 하위 LLM 생성 행태에 미친 간접 효과.

### Grounding Filter 자체 버그도 하나 더 발견·수정

v7의 "우리은행" 관련 LLM 출력이 괄호를 포함한 서술형 문장("...당사자들(NH농협은행, 우리은행 외
1곳, 우리은행 외 2곳): ...")으로 나오자, 기존 Grounding Filter의 단순 콤마 분리 로직이 **괄호
중간에서 잘라버려** 정상 추출된 "우리은행"을 필터가 오히려 삭제하는 버그를 발견(Recall
100%→80%로 잘못 표시됨). `split_top_level()`(괄호 깊이 추적) + `extract_candidates()`(괄호
안 개별 항목도 후보로 검증)로 수정, v5/v6c 재검증 결과 기존 수치와 동일해 회귀 없음 확인
(`postprocess_grounding_filter.py`).

### [18] 최종 판정

**품질 관점**: TATR 채택은 명백한 승리 — Recall 90%→**100%**(이 프로젝트 사상 최초 만점), F1
92.2%→**96.6%**. Precision은 소폭 하락(94.4%→93.3%)하지만 page2의 기존 할루시네이션 문제(표
라우팅과 무관, [14]에서 이미 발견된 별개 이슈)가 그대로 남아있어서지 TATR 자체 문제가 아님.

**지연 관점**: 표 단계만 보면 3배 빠르지만(12.16→4.11초), 하위 LLM이 더 풍부해진 정보에 반응해
더 길게 생성하면서 전체 지연은 오히려 6.6% 증가(462.8→493.25초). **"표 처리 latency 최적화"라는
좁은 목표만 보면 TATR이 이겼지만, "전체 파이프라인 latency"까지 보면 이번엔 소폭 손해** — 이 상충은
표 처리팀 단독으로 해결할 수 있는 범위가 아니라, 하위 엔티티 추출 프롬프트/생성 파라미터 팀과
같이 조율해야 하는 문제로 남겨둠(예: page3류 "설명형" 답변 대신 "기업명만 한 줄씩" 프롬프트를
더 엄격히 강제하면 정보 이득은 유지하면서 생성 길이만 줄일 수 있을 것으로 예상 — 미검증).

**최종 권고**: 표 처리 담당 범위 안에서는 **TATR(adaptive_padding+300dpi)+pdfplumber로 교체를
권고**(Recall 최초 100%, 표 단계 자체는 3배 빠름) — 단, 하위 엔티티 추출 단계와 연동 시 생성
길이 증가로 인한 총 지연 트레이드오프가 있다는 점을 명시적으로 인수인계할 것.

---

## 종합 결론

| 구성요소 | 채택 | 근거 |
|---|---|---|
| 표 위치→내용 추출 | **Docling(TableFormer)**, YOLO 크롭 단위 | pdfplumber 대비 8배(30→240행) |
| 처리 방식 | **프로세스 병렬**(동적 워커, 웜풀, MAX_WORKERS=8) | 품질 손실 0%, 지연 -61%. 워커 10/12개로 늘려봤지만 코어 경합으로 악화 확인(더 시도할 가치 없음) |
| 배치 처리 / 표크기 라우팅([2],[4]) | 기각 | 품질손실 > 지연절감 |
| 크롭 고도화(패딩+캡션매핑+DPI 재렌더링, [12]) | 기각 | YOLOv11n 품질·지연 둘 다 악화, YOLOv26n은 소폭 개선해도 여전히 YOLOv11n 미달 |
| Adaptive Table Complexity Router([13], fill_ratio 기반) | **채택**(표 단계 자체 지연 이득은 이 표본에서 미미하나, 크기 기반 라우팅의 실패 위험 없이 안전) | [4]의 실패(크기≠복잡도) 해결, Recall 유지 |
| **Table-aware Entity Extraction 분기([14], 핵심 고도화)** | **채택** | 병목은 표 추출(1%)이 아니라 엔티티 추출(54~63%)임을 직접 측정 후 타겟팅 — 총 지연 **-57.8%**, Precision/F1도 개선(공정 비교 기준 81.2%→94.4%) |
| Grounding Filter(할루시네이션 후처리 안전장치) | **채택(프로덕션 필수)** | 표를 LLM에서 제외하자 반대급부로 생긴 신종 할루시네이션(가짜 회사명 연쇄생성)을 잡아냄. 근사 Precision 지표만으론 착시가 생겨 반드시 필요. 괄호 포함 서술형 출력에서 괄호 중간이 끊겨 정답까지 삭제되는 버그도 발견·수정([18]) |
| max_new_tokens 축소(200→150) | **채택**(보조적) | 추가 지연 절감(-3.8%), 단 할루시네이션 근본 해결은 아님(양만 감소) — Grounding Filter를 대체 못 함 |
| repetition_penalty=1.3 | **유지** | Recall 60→90%, 1.5 이상은 할루시네이션 유발(재확인 완료) |
| **TATR(adaptive_padding+300dpi)+pdfplumber로 표 엔진 교체([16]~[18], 최종 고도화)** | **채택(표 처리 최종 권고)** | COMPLEX 표 처리를 Docling→TATR로 교체 — Recall **90%→100%**(사상 최초 만점, "우리은행" 미스 해소), 표 단계 자체 3배 빠름(12.16→4.11초). 단 하위 LLM이 더 풍부해진 정보에 반응해 더 길게 생성하며 총 지연은 소폭 증가(462.8→493.25초, +6.6%) — 순수 표 처리 관점에선 명백한 승리, 전체 파이프라인 지연은 엔티티 추출팀과 조율 필요 |

**최종 수치 비교**:

| 지표 | 최초 베이스라인(v1, 표만 pdfplumber) | 이전 최선(v2+penalty) | Docling 최종(v6c) | **TATR 최종(v7, 표 처리 권고안)** |
|---|---|---|---|---|
| Recall | 60.0% | 90.0%(9/10) | 90.0%(9/10) | **100.0%(10/10) — 최고** |
| Precision(grounded) | - | 81.2% | 94.4% | 93.3% |
| F1(grounded) | - | 85.4% | 92.2% | **96.6% — 최고** |
| 표 단계 소요 | (pdfplumber, 거의 무료) | (Docling 도입 전) | 12.16초 | **4.11초 — 최고** |
| 총 처리시간 | 468.7초 | 1097.51초 | 462.8초 | 493.25초 |

**해석**: 표 처리 담당 범위(표 단계 latency + 표 추출이 Recall에 미치는 영향)만 놓고 보면 **TATR이
전 지표에서 Docling을 이기거나 동률**(Recall/F1/표단계속도 전부 최고, Precision만 근소 하락하는데
이마저도 표 라우팅과 무관한 page2의 기존 이슈 탓). 총 파이프라인 지연만 유일하게 역전되는데, 이는
표 처리가 만들어낸 "더 정확한 표 데이터"에 하위 LLM이 더 길게 반응해서 생긴 하류 부작용 — 표
처리팀의 개선이 오히려 표처리팀 책임 범위 밖(엔티티 추출 프롬프트 설계)의 튜닝을 요구하게 된 case.

**남은 병목/다음 과제** (우선순위순, [18] 이후 재산정):
1. **[최우선, 표처리 범위 밖] 페이지 분류+텍스트+이미지 캡셔닝(VLM) 단계가 여전히 최대 병목** — 390.6초,
   전체의 79~84%(v7 기준 79.2%)를 차지(표 단계 4.1초=0.8%, 엔티티 추출 98.6초=20%). 이 단계는 이번
   table_processing 고도화 전 과정에서 한 번도 손대지 않고 `memory_store.json`을 그대로 재사용해왔음
   — 담당 팀원의 이미지 처리 파트 소관. Qwen3-8B 교체 시 재측정 필요.
2. **[표처리↔엔티티추출 경계 이슈]** TATR 채택 시 엔티티 추출 단계가 늘어나는 부작용(+38.5초, page3
   호출이 13→27.3초) — LLM이 "기업명만 한 줄씩" 대신 서술형으로 답하는 경향이 원인으로 추정. 표
   처리팀 단독 해결 범위 밖, 엔티티 추출 프롬프트를 더 엄격히 강제하면 해소될 가능성 있음(미검증)
3. TableFormer/TATR을 Docling 오케스트레이션 없이 직접 호출하는 흐름은 이미 [16]~[18]에서 구현·검증
   완료(더 이상 "미검증 후보"가 아님)
4. Adaptive Router가 자체적으로 다시 수행하는 YOLO 재탐지(~1.7초 오버헤드) — page_classification 단계의
   기존 탐지 결과 재사용으로 제거 가능(미검증, 이제 표 단계 자체가 4초대라 상대적으로 비중은 커졌으나
   절대 시간은 여전히 작음)
5. **PDF 1건 기준 결론** — 다른 양식 PDF 몇 개로 재검증 필요(특히 TATR+pdfplumber는 텍스트 레이어가
   없는 스캔 PDF에서는 무용지물이라 Docling의 내장 OCR로 폴백하는 조건 분기가 실제 배포 전 필요)

### 향후 로드맵 (사용자 제안 기법들 검토 — 우선순위 판단)

사용자가 제안한 기법들(TableBank/PubTables-1M/Table Transformer(TATR)/Donut/Pix2Struct 논문 기반)을
검토한 결과, **이번에 실제로 측정된 병목 구조를 반영해 우선순위를 재산정**하면:

| 순위 | 기법 | 판단 |
|---|---|---|
| 1 | **VLM(이미지 캡셔닝) 단계 최적화** | 사용자 제안엔 없었지만 이번 실측으로 새로 드러난 **실제 1순위**(전체의 84%) |
| 2 | Schema-guided Entity Extraction(LLM에 전체 생성 대신 검증만 시키기) | [14]와 같은 방향성(LLM 부담 축소) — 남은 엔티티 추출 60초를 더 줄일 여지, 할루시네이션도 원천 차단 가능. **2순위로 재검증 가치 있음** |
| 3 | Learned Table Complexity Classifier(MobileNetV3 등) | [13]의 rule-based 라우터가 이미 [4]의 실패 원인을 해결하고 검증됨 — 학습 기반은 데이터/라벨링 비용 대비 이득이 불확실. **표 단계가 전체의 2.6%뿐이라 우선순위 낮음** |
| 4 | TableFormer 직접 호출(Docling 오케스트레이션 생략) | 표 단계가 이제 전체의 2.6%뿐이라 효과가 제한적. 여전히 미검증 상태로 기록만 유지 |
| 5 | Donut/Pix2Struct(OCR-free) | 이번에 발견한 "Docling OCR이 한글 라벨을 깨뜨리는" 문제의 근본 해결책이 될 수 있어 흥미롭지만, 표 단계 자체 비중이 작아진 지금은 급하지 않음 |
| 6 | 3-stage Parser(Simple/Medium/Hard) | [13]의 2-stage(Simple/Complex)로 이미 크기≠복잡도 문제는 해결됨 — 표 단계 비중이 작아 3단계로 세분화할 실익이 작음 |
| 7 | Table Structure Post-processing(병합 셀 복원 등) | Docling의 한글 OCR 오류(위 버그 발견)가 먼저 해결돼야 의미 있음 — 선행 조건 미충족 |

**결론**: 사용자가 제안한 논문 기반 기법들은 대부분 "표 추출을 더 정교하게"에 초점이 맞춰져 있었으나,
이번 실측 결과 표 추출은 이미 전체 지연의 2.6%까지 줄어들어 추가 정교화의 ROI가 낮다. 반대로 사용자가
"future"로 남겨둔 이미지/VLM 캡셔닝 단계가 이번 실측으로 새로운 최우선 과제로 드러났다 — 다음 세션은
이 지점부터 시작하는 것을 권장.
