# 실험 기록 — 페이지 분류 (Page Classification)

## 범위
페이지가 텍스트/표/이미지 중 무엇을 포함하는지 판별하고, 표는 위치(bbox)까지 찾아 크롭한다.
**표/이미지 내용을 실제로 해석·추출하는 것은 이 범주 밖**(→ `../table_processing/`로 이동).

## 대상 문서
- `reference/20260721_company_279243000.pdf` (교보증권 LG CNS(064400) 기업분석, 6페이지)
- 정답: `ground_truth_pages.json` (페이지별 실제 has_text/has_table/has_image 라벨)

## 평가 우선순위
**Recall > Precision**, 지연은 감소하면서 성능 저하가 크지 않으면 채택.

---

## [1] Baseline: pdfplumber + PyMuPDF 결합 ("PyMuPDF Fast Scan")

- 기법: pdfplumber `find_tables()`(표 감지) + PyMuPDF 래스터 이미지 수/벡터 드로잉 수(이미지 감지) 결합. LLM 미사용, 메타데이터만 검사
- 코드: `benchmark_baseline.py`

| 라벨 | Accuracy | Precision | Recall | F1 |
|---|---|---|---|---|
| has_text | 100.0% | 100.0% | 100.0% | 100.0% |
| has_table | 83.3% | 100.0% | 83.3% | 90.9% |
| has_image | 66.7% | 66.7% | 100.0% | 80.0% |

- 전체 라벨 정확도: 83.3%(18개 중), 페이지 완전일치: 3/6
- 지연: 평균 161.8ms/page — LLM 미사용이라 매우 빠름

**오류**: has_table 미탐(page3, 테두리선 약함) / has_image 오탐(page4·6, 표 격자선을 벡터 드로잉으로 오인)

## [2] + YOLOv11n Crop (채택)

- 기법: `Armaggheddon/yolo11-document-layout`(YOLOv11n, DocLayNet 11클래스)로 페이지 렌더링 이미지에서 레이아웃 감지, 'Table'/'Picture' 클래스로 판정. Table bbox는 크롭 저장(`table_crops/`)
- 코드: `benchmark_yolo_crop.py`

| 라벨 | Accuracy |
|---|---|
| has_text / has_table / has_image | 전부 **100.0%** |

- 페이지 완전일치: **6/6**, 지연 평균 212.2ms/page(워밍업 후)
- baseline의 두 오류(표 미탐, 이미지 오탐) 전부 해결

## [비교] YOLOv26n

- `Armaggheddon/yolo26-document-layout`(2026-01-14 출시, 공식 43% 빠른 CPU 추론 주장)로 교체 테스트
- 코드: `benchmark_yolo26_crop.py`

| 항목 | YOLOv11n | YOLOv26n |
|---|---:|---:|
| Page Classification 정확도 | 100% | 100%(동률) |
| 지연 | 212.2ms/page | 219.4ms/page(체감 차이 없음) |
| Table 크롭 수 | 14 | 13 |

**판정**: 페이지 분류 정확도는 동률. 표 crop 개수 차이(14 vs 13)가 표 내용 추출 품질에 미치는 영향은 `../table_processing/`에서 다룸(그 결과 YOLOv11n이 더 우수 — page_classification 범주 밖의 결론이라 여기선 판정 보류).

## [3] 표 크롭 고도화: Adaptive Padding + Caption 공간매핑 + DPI 부분 재렌더링

YOLOv26n의 타이트한 bbox가 표 구조 인식 저하([비교]의 240→149행 격차)의 원인일 수 있다는 가설 하에, 크롭 단계에서 보완 가능한지 검증. YOLOv11n/YOLOv26n 둘 다에 동일 로직 적용.

- 기법:
  1. **Adaptive Padding**: 150dpi 픽셀 기준 상단 +35px(캡션이 자연스럽게 포함되도록) / 좌우·하단 +12px(타이트하게 — page4처럼 표가 밀집된 레이아웃에서 인접 표를 침범하지 않도록)
  2. **Spatial Nearest Caption Mapping**: 표 bbox 상단-중심점과 'Caption'/'Section-header' bbox 하단-중심점 간 유클리드 거리를 계산해, 표 바로 위(y좌표 기준)에 있는 것 중 최근접 1개를 결합. 단 거리가 200px을 넘으면 "전용 캡션 없음"으로 처리(밀집 페이지에서 억지 매칭 방지 — 처음엔 상한 없이 최근접을 무조건 매칭했더니 966~1168px 떨어진, 명백히 무관한 캡션까지 결합되는 문제가 있어 수정)
  3. **DPI Sub-rendering**: YOLO 탐지는 150dpi 그대로(속도 유지), 탐지+패딩된 bbox만 PyMuPDF `clip` 파라미터로 원본 PDF에서 300dpi로 부분 재렌더링
- 코드: `benchmark_enhanced_crop.py`

크롭 생성 결과(캡션 매칭 커버리지):

| 모델 | 표 개수 | 캡션 매칭(200px 이내) | 매칭 안 됨 | 매칭 거리 범위 |
|---|---|---|---|---|
| YOLOv11n | 14 | 3개(21%) | 11개 | 81~140px |
| YOLOv26n | 13 | 4개(31%) | 9개 | 73~183px |

- 관찰: page4(표 6개 밀집)는 표마다 전용 캡션/소제목이 없는 경우가 많음(공용 섹션 헤더 1개를 여러 표가 공유하는 구조로 추정) — 정직한 거리 임계값(200px)을 적용하니 다수 표가 "캡션 없음"으로 남음. 매칭된 표들의 거리(73~183px)는 실제로 타당해 보여 임계값 자체는 합리적으로 작동
- 산출물: `table_crops_enhanced_yolo11/`(14개), `table_crops_enhanced_yolo26/`(13개), 각 `_meta.json`(원본/패딩 bbox, 캡션 매칭 정보, 렌더링 DPI 기록)
- **표 내용 추출 품질(Docling 행수)에 대한 실제 효과는 `../table_processing/실험.md` [12]에서 측정** — 결론: YOLOv11n은 품질·지연 둘 다 악화, YOLOv26n은 소폭 개선하나 여전히 YOLOv11n에 못 미침 → 이 고도화 기법은 **기각**, page_classification 단계의 크롭 방식은 변경하지 않음

### 대조군: 패딩만 단독(캡션매핑·DPI 변경 없음)

"패딩"과 "DPI 재렌더링" 중 어느 쪽이 [3]의 결과를 만들었는지 분리하기 위해, 150dpi 그대로 사방 12px 균일 패딩만 추가한 크롭을 별도 생성.

- 코드: `benchmark_padding_only_crop.py` (`table_crops_padonly_yolo11/`, `table_crops_padonly_yolo26/`)
- Docling 측정 결과(`../table_processing/실험.md` [12] 대조군 참고): **패딩 단독은 YOLOv11n 품질을 오히려 떨어뜨리고(240→220행) YOLOv26n은 거의 변화 없음(149→148행)** — [3]에서 관찰된 YOLOv26n의 개선(+15행)은 패딩이 아니라 DPI 300 재렌더링이 원인이었고, YOLOv11n의 악화는 DPI가 아니라 패딩 자체가 원인이었음(지연 폭증만 DPI 탓)

---

## [4] 다른 섹터 PDF로 일반화 검증 — 사상 첫 재검증(K-Wave 산업 리포트, 73페이지)

**모든 결론이 "PDF 1건(LG CNS, 6페이지) 기준"이라는 한계를 여기서 처음 해소.** 완전히 다른 섹터
(음식료·미디어·엔터, DS투자증권 "Beyond K-Wave" 산업 리포트)·다른 규모(6페이지→73페이지)의 PDF로
baseline vs YOLOv11n을 재검증.

- 대상: `reference/KWave/20260721_industry_65157000.pdf`(73페이지, 10개 기업 다룸)
- 정답: 13개 표본 페이지(표지/목차/산업분석 텍스트+차트/기업 재무데이터/디스클레이머 등 다양한
  유형을 대표하도록 육안 선정) 육안 검수 — `ground_truth_kwave_pages.json`
- 코드: `benchmark_kwave_validation.py`

| 지표 | Baseline | **YOLOv11n** |
|---|---|---|
| 전체 라벨 정확도(39개 중) | 71.8%(28/39) | **100.0%(39/39)** |
| has_text | 92.3% | **100.0%** |
| has_table | 53.8% | **100.0%** |
| has_image | 69.2% | **100.0%** |
| 페이지 완전일치 | 5/13 | **13/13** |

**LG CNS에서 발견된 baseline의 실패 패턴이 완전히 다른 PDF에서도 그대로 재현됨**:
- has_table 미탐(53.8%로 가장 취약) — 연한 테두리의 "Financial Data" 표(하이브/에스엠/스튜디오
  드래곤 등 기업 섹션마다 반복 등장하는 표 스타일)를 반복적으로 놓침(page28, 31, 36, 65, 73)
- has_table 오탐도 새로 발견(page21) — 차트 내부의 격자선을 표로 오인(벡터 드로잉을 표 테두리로
  착각하는 LG CNS의 has_image 오탐과 같은 계열의 실패 모드)
- has_image 미탐(69.2%) — 주가 차트를 놓침(page28, 36, 65)

**결론**: YOLOv11n 채택 결정이 PDF 특성(레이아웃/폰트/섹터)에 우연히 맞아떨어진 게 아니라
**진짜 일반화되는 개선**임을 확인. "PDF 1건 기준" 캐비어트는 page_classification 범주에서는 해소.

## [5] 세 번째 섹터 PDF로 재검증(Construct, 건설 Weekly, 하나증권, 10페이지)

K-Wave(엔터/식품/미디어)에 이어 **건설업 섹터**로 재검증. 10페이지로 적어 샘플링 없이 **전 페이지
육안 전수 검수**로 정답 작성.

- 대상: `reference/Construct/20260721_industry_362851000.pdf`
- 정답: 10페이지 전체 육안 전수 검수 — `ground_truth_construct_pages.json`
- 코드: `benchmark_construct_validation.py`

| 지표 | Baseline | **YOLOv11n** |
|---|---|---|
| 전체 라벨 정확도(30개 중) | 83.3%(25/30) | **93.3%(28/30)** |
| 페이지 완전일치 | 5/10 | **8/10** |

K-Wave(71.8%→100%)만큼 격차가 크진 않음 — 이 리포트는 표/차트 경계가 시각적으로 더 뚜렷해
baseline도 상대적으로 잘 맞았음(has_table을 pdfplumber `find_tables()`가 아니라 baseline 자체
로직으로도 여러 표를 놓치지 않음). YOLOv11n의 유일한 오답은 page4(전국 아파트지수를 지역별 격자
히트맵으로 시각화)를 Table로 판정한 것 — "테두리 있는 셀에 숫자가 빽빽한 격자"라는 시각 패턴이
실제 표와 매우 흡사해, 모델 판단이 명백히 틀렸다고 보기 어려운 경계 사례(지도형 시각화 vs 표
구분 문제로 기록, 세 PDF에서 처음 나타난 실패 유형).

**결론**: 두 번째 재검증에서도 YOLOv11n이 baseline을 상회 — "PDF 1건/2건 기준" 우연이 아님을
추가로 확인. 다만 새 실패 유형(지도형 시각화 오탐)이 매 섹터마다 하나씩 새로 나타나는 패턴이
계속됨(K-Wave의 벡터 드로잉 오탐, LG CNS의 has_image 오탐과 같은 계열).

## [6] 병목 스캔 — 공유 유틸 `run_yolo_layout()`의 불필요한 디스크 왕복 제거

사용자 지시("병목 찾아서 해결해줘. 텍스트, 테이블, 페이지 분류 파이프라인 내에서")로 `classify_pdf()`를
cProfile로 스캔. 페이지 렌더링 결과를 **PNG로 디스크에 저장했다가 곧바로 다시 읽어들이는** 왕복이
`pdf_pipeline/yolo_layout.py`의 `run_yolo_layout()`(page_classification/text_processing/
table_processing이 전부 공유)에 있었음 — `pix.samples`를 `Image.frombytes()`로 바로 PIL
이미지 변환하도록 교체(픽셀 단위 완전 동일 결과 numpy로 검증). K-Wave(73페이지) 기준
`classify_pdf()` **7.71s → 5.09s**(34% 단축). 상세 내용/실측치는 `text_processing/실험.md [33]`
참고(공유 유틸이라 그쪽에 자세히 기록) — 여기선 page_classification 자체 결과만 요약. LGCNS/
Construct 재검증 결과 라벨 정확도 변화 없음(회귀 없음, 순수 성능 최적화).

---

## 최종 결론 (page_classification 범주)

**채택: YOLOv11n, 가공 없는 플레인 크롭** — 라벨 정확도 100%(LG CNS), 지연 212ms/page. **두 차례
재검증**(K-Wave 73p: 71.8%→100%, Construct 10p: 83.3%→93.3%)에서 모두 baseline을 상회해 일반화
확인. [3]의 패딩/캡션매핑/DPI 고도화는 표 내용 추출 품질을 개선하지 못해(오히려 YOLOv11n은 악화)
도입하지 않음. 이 범주의 개선은 여기서 마무리.

산출물(다음 단계 `table_processing/`의 입력):
- `table_crops/` — YOLOv11n이 찾은 Table 영역 크롭 14개(채택, 플레인)
- `table_crops_yolo26/` — YOLOv26n이 찾은 Table 영역 크롭 13개(비교용)
- `table_crops_enhanced_yolo11/`, `table_crops_enhanced_yolo26/` — [3] 고도화 크롭(비교/기각용, 참고 자료로만 보존)
- `table_crops_kwave/` — K-Wave PDF에서 YOLOv11n이 찾은 표 크롭 104개([4] 검증용)
- `table_crops_construct/` — Construct PDF에서 YOLOv11n이 찾은 표 크롭 15개([5] 검증용)
